# Автопризнаки

## Настройки

In [1]:
%pip -q install "numpy>=1.24" "numba>=0.59" "pyarrow>=16" "catboost>=1.2" "huggingface_hub>=0.30" tqdm

In [26]:
import gc, json, time, shutil, os, hashlib, ctypes, psutil
from pathlib import Path
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
import torch
from torch import nn
from torch.nn import functional as F
from numba import njit
from tqdm.auto import tqdm
from catboost import CatBoostClassifier
from huggingface_hub import hf_hub_download
from sklearn.metrics import roc_auc_score, log_loss
from IPython.display import display
from google.colab import drive

drive.mount('/content/drive')
ROOT = Path('/content/drive/MyDrive/TLab_Yambda')
DATA = ROOT / 'retrieval_gts_v2'
R2 = ROOT / 'catboost_reranking_v1'
OUT = ROOT / 'adaptive_bins_autofe_sparse_v3'
LOCAL = Path('/content/yambda_adaptive_bins_sparse_v3')
OUT.mkdir(parents=True, exist_ok=True)
LOCAL.mkdir(parents=True, exist_ok=True)

SEED = 42
C = 600
DAY = 86_400
GAP = 1_800
N_COARSE = 6
N_CHANNELS = 10
Z_DIM = 64
HIST_DAYS = 10
HIST_POS_PER_USER = 8
NEG = 12
BATCH_GROUPS = 384
ENC_EPOCHS = 16
ENC_LR = 5e-4
ENC_PATIENCE = 4
CB_NEG_PER_USER = 100
CB_EVAL_USERS = 512
CB_TREES, CB_DEPTH, CB_LR = 500, 8, 0.05
INFER_BATCH = 4096
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
RAM_SHARE = 0.48
RAM_MAX_GIB = 3.0


FINE_EDGES = np.r_[np.expm1(np.linspace(0, np.log1p(365), 24)), 1e8].astype(np.float32)
NF = len(FINE_EDGES)-1
FINE_CENTERS = np.r_[(np.log1p(FINE_EDGES[:-2]) + np.log1p(FINE_EDGES[1:-1]))/2,
                     np.log1p(730.)].astype(np.float32)

rng = np.random.default_rng(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
users = pd.read_csv(DATA/'selected_users.csv').uid.to_numpy(dtype=np.uint32)
N_USERS = len(users)
snaps = pd.read_csv(DATA/'snapshots.csv').set_index('split')
print('Device:',DEVICE,'users:',N_USERS,'technical bins:',NF)
display(snaps)

config = dict(storage='sparse_bins_v3',seed=SEED, fine_edges_days=FINE_EDGES.tolist(), n_coarse=N_COARSE,
              n_channels=N_CHANNELS, z_dim=Z_DIM, hist_days=HIST_DAYS,
              hist_pos_per_user=HIST_POS_PER_USER, neg=NEG, batch_groups=BATCH_GROUPS,
              encoder_epochs=ENC_EPOCHS, encoder_lr=ENC_LR, gap_seconds=GAP)
(OUT/'config.json').write_text(json.dumps(config,indent=2))

import subprocess, sys
with (OUT/'requirements-lock.txt').open('w') as lockfile:
    subprocess.run([sys.executable, '-m', 'pip', 'freeze'], stdout=lockfile, check=True)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Device: cuda users: 10000 technical bins: 24

       snapshot_id    cutoff  history_end       end
split
train            0  25737200     25735400  25823600
valid            1  25825400     25823600  25911800
test             2  25913600     25911800  26000000

834

## История

In [3]:
cols = ['uid','item_id','timestamp','event_type','played_ratio_pct',
        'is_organic','track_length_seconds','positive']
events = pd.read_parquet(DATA/'events_sample.parquet', columns=cols)
events = events.sort_values('timestamp',kind='stable').reset_index(drop=True)
EU = pd.Index(users).get_indexer(events.uid).astype(np.int32)
EI_RAW = events.item_id.to_numpy(dtype=np.uint32)
ET = events.timestamp.to_numpy(dtype=np.int64)
ER = np.nan_to_num(events.played_ratio_pct.to_numpy(dtype=np.float32),nan=0.)/100
EO = events.is_organic.fillna(False).to_numpy(dtype=np.uint8)
EL = np.nan_to_num(events.track_length_seconds.to_numpy(dtype=np.float32),nan=0.)
EK = np.full(len(events),6,dtype=np.uint8)
kind = events.event_type.astype(str)
for label,idx in [('listen',0),('like',2),('unlike',3),('dislike',4),('undislike',5)]:
    EK[kind.eq(label).to_numpy()] = idx
EK[(EK==0)&events.positive.to_numpy(dtype=bool)] = 1
items = np.unique(EI_RAW)
EI = np.searchsorted(items,EI_RAW).astype(np.int32)
N_ITEMS = len(items)
del events,kind

artist_file = hf_hub_download(repo_id='yandex/yambda',repo_type='dataset',
                               filename='artist_item_mapping.parquet')
art = pd.read_parquet(artist_file,columns=['item_id','artist_id']).dropna().drop_duplicates()
art = art[art.item_id.isin(items)].sort_values(['item_id','artist_id'])
ai = np.searchsorted(items,art.item_id.to_numpy(dtype=np.uint32))
acount = np.bincount(ai,minlength=N_ITEMS)
APTR = np.r_[0,np.cumsum(acount,dtype=np.int64)]
ART = art.artist_id.to_numpy(dtype=np.uint32)
del art,ai,acount
print('Events:',f'{len(ET):,}','Items:',f'{N_ITEMS:,}','Artist links:',f'{len(ART):,}')

Events: 47,790,449 Items: 934,057 Artist links: 928,796

## Агрегаты

In [4]:
@njit
def locate(keys,value):
    lo,hi = 0,len(keys)
    while lo<hi:
        mid=(lo+hi)//2
        if keys[mid]<value: lo=mid+1
        else: hi=mid
    return lo if lo<len(keys) and keys[lo]==value else -1

@njit
def mark_relations(u,raw,item_idx,artist_ptr,artist_ids,ui_keys,ua_keys):
    seen_ui=np.zeros(len(ui_keys),np.uint8)
    seen_ua=np.zeros(len(ua_keys),np.uint8)
    for e in range(len(u)):
        prefix=np.uint64(u[e])<<np.uint64(32)
        p=locate(ui_keys,prefix|np.uint64(raw[e]))
        if p>=0: seen_ui[p]=1
        it=item_idx[e]
        for a in range(artist_ptr[it],artist_ptr[it+1]):
            q=locate(ua_keys,prefix|np.uint64(artist_ids[a]))
            if q>=0: seen_ua[q]=1
    return seen_ui,seen_ua

@njit
def put(state,row,b,event,played,organic,length):
    state[row,b,event]+=1.
    if event<2:
        state[row,b,7]+=played
        state[row,b,8]+=organic
        state[row,b,9]+=length/300.

@njit
def aggregate_history_into(U,I,UI,UA,last_u,last_i,last_ui,first_ui,
                           last_ratio,like,dislike,last_ua,
                           u,raw,item_idx,ts,kind,ratio,organic,length,
                           hist_end,edges,ptr,artists,ui_keys,ua_keys,ui_map,ua_map):

    for e in range(len(u)):
        age=(hist_end-ts[e])/86400.
        b=0
        while b<len(edges)-2 and age>=edges[b+1]: b+=1
        uid,it,event=u[e],item_idx[e],kind[e]
        put(U,uid,b,event,ratio[e],organic[e],length[e])
        put(I,it,b,event,ratio[e],organic[e],length[e])
        last_u[uid]=ts[e]
        last_i[it]=ts[e]
        prefix=np.uint64(uid)<<np.uint64(32)
        p=locate(ui_keys,prefix|np.uint64(raw[e]))
        if p>=0 and ui_map[p]>0:
            j=ui_map[p]
            put(UI,j,b,event,ratio[e],organic[e],length[e])
            last_ui[j]=ts[e]
            if first_ui[j]<0: first_ui[j]=ts[e]
            if event<2: last_ratio[j]=ratio[e]
            if event==2: like[j]=1.
            elif event==3: like[j]=0.
            elif event==4: dislike[j]=1.
            elif event==5: dislike[j]=0.
        for a in range(ptr[it],ptr[it+1]):
            q=locate(ua_keys,prefix|np.uint64(artists[a]))
            if q>=0 and ua_map[q]>0:
                j=ua_map[q]
                put(UA,j,b,event,ratio[e],organic[e],length[e])
                last_ua[j]=ts[e]


def save_dense_bins(folder,name,raw,chunk=8192):
    arr=np.lib.format.open_memmap(folder/f'{name}.npy',mode='w+',
                                  dtype=np.float16,shape=raw.shape)
    for start in range(0,len(raw),chunk):
        stop=min(start+chunk,len(raw))
        arr[start:stop]=np.log1p(raw[start:stop]).astype(np.float16)
    arr.flush()
    del arr


def save_sparse_bins(folder,name,raw,chunk=8192):

    nr=len(raw)
    ptr=np.zeros(nr+1,dtype=np.int64)
    for start in range(0,nr,chunk):
        stop=min(start+chunk,nr)
        count=np.count_nonzero(np.any(raw[start:stop]!=0,axis=2),axis=1)
        ptr[start+1:stop+1]=np.cumsum(count,dtype=np.int64)+ptr[start]
    np.save(folder/f'{name}_ptr.npy',ptr)
    nnz=int(ptr[-1])
    bins=np.lib.format.open_memmap(folder/f'{name}_bin.npy',mode='w+',
                     dtype=np.uint8,shape=(nnz,))
    vals=np.lib.format.open_memmap(folder/f'{name}_val.npy',mode='w+',
                     dtype=np.float32,shape=(nnz,N_CHANNELS))
    for start in range(0,nr,chunk):
        stop=min(start+chunk,nr)
        block=raw[start:stop]
        local_row,local_bin=np.nonzero(np.any(block!=0,axis=2))
        off=int(ptr[start])
        sz=len(local_bin)
        bins[off:off+sz]=local_bin.astype(np.uint8)
        vals[off:off+sz]=np.log1p(block[local_row,local_bin])
    bins.flush(); vals.flush()
    del bins,vals
    print(f'  {name}: {nr:,} rows, {nnz:,} nonempty time bins',flush=True)


@njit
def gather_sparse_bins(ptr,bins,vals,rows,nf,nc):
    out=np.zeros((len(rows),nf,nc),np.float32)
    for j in range(len(rows)):
        r=rows[j]
        for k in range(ptr[r],ptr[r+1]):
            b=bins[k]
            for c in range(nc):
                out[j,b,c]=vals[k,c]
    return out

## Исторические задачи

In [5]:
def historical_candidates(cutoff,seed):
    generator=np.random.default_rng(seed)
    hist_end=cutoff-GAP
    n=np.searchsorted(ET,hist_end,side='left')
    hi=np.searchsorted(ET,cutoff+DAY,side='left')
    lo=np.searchsorted(ET,cutoff,side='left')
    counts=np.bincount(EI[:n][EK[:n]==1],minlength=N_ITEMS)
    catalog=np.flatnonzero(counts>0)
    probs=np.power(counts[catalog].astype(np.float64),.75)
    probs/=probs.sum()
    positive=pd.DataFrame({'u':EU[lo:hi][EK[lo:hi]==1],
                           'item':EI_RAW[lo:hi][EK[lo:hi]==1]}).drop_duplicates()
    positive=positive[positive.item.isin(items[catalog])]
    day_positive={int(u):set(g.item.to_numpy().tolist()) for u,g in positive.groupby('u')}
    positive=positive.iloc[generator.permutation(len(positive))]
    positive=positive.groupby('u',sort=False).head(HIST_POS_PER_USER).reset_index(drop=True)
    m=len(positive)

    recent_from=np.searchsorted(ET,hist_end-30*DAY,side='left')
    recent=pd.DataFrame({'u':EU[recent_from:n],'item':EI_RAW[recent_from:n]})
    recent=recent.drop_duplicates(['u','item'],keep='last').groupby('u',sort=False).tail(40)
    recent_pools={int(u):g.item.to_numpy(dtype=np.uint32) for u,g in recent.groupby('u')}
    pop_draws=items[generator.choice(catalog,size=(m,NEG*3),p=probs)]
    result=np.empty((m,NEG+1),np.uint32)
    result[:,0]=positive.item.to_numpy(dtype=np.uint32)
    for j,(u,raw) in enumerate(positive[['u','item']].itertuples(index=False,name=None)):
        forbidden=day_positive[int(u)]
        pool=recent_pools.get(int(u),())
        used={int(raw)}
        cursor=0
        for k in range(1,NEG+1):
            choice=None
            if k%2==0 and len(pool):
                for _ in range(8):
                    q=int(pool[generator.integers(len(pool))])
                    if q not in forbidden and q not in used:
                        choice=q
                        break
            while choice is None and cursor<NEG*3:
                q=int(pop_draws[j,cursor]); cursor+=1
                if q not in forbidden and q not in used: choice=q
            if choice is None:
                forbidden_items=np.fromiter(forbidden|used,dtype=np.uint32)
                available=np.setdiff1d(items[catalog],forbidden_items,assume_unique=False)
                choice=int(generator.choice(available))
            result[j,k]=choice
            used.add(choice)
    return pd.DataFrame({'uid':users[np.repeat(positive.u.to_numpy(dtype=np.int32),NEG+1)],
                         'item_id':result.ravel(),
                         'label':np.tile(np.r_[1,np.zeros(NEG,dtype=np.uint8)],m)})

train_history_end=int(snaps.loc['train'].history_end)
hist_days=pd.DataFrame([dict(name=f'hist_{j}',cutoff=train_history_end-(HIST_DAYS-j)*DAY,
                             history_end=train_history_end-(HIST_DAYS-j)*DAY-GAP)
                        for j in range(HIST_DAYS)])
display(hist_days)
print('Last historical target ends at',hist_days.cutoff.max()+DAY,
      '; main train history ends at',train_history_end)

     name    cutoff  history_end
0  hist_0  24871400     24869600
1  hist_1  24957800     24956000
2  hist_2  25044200     25042400
3  hist_3  25130600     25128800
4  hist_4  25217000     25215200
5  hist_5  25303400     25301600
6  hist_6  25389800     25388000
7  hist_7  25476200     25474400
8  hist_8  25562600     25560800
9  hist_9  25649000     25647200

Last historical target ends at 25735400 ; main train history ends at 25735400

## Снапшоты

In [6]:
STORE_VERSION = 'sparse_fast_verified_v2'
STORE_KEYS = ('u','i','ui_ptr','ui_bin','ui_val','ua_ptr','ua_bin','ua_val',
              'u_last','i_last','ua_last','ui_meta','cand_u','cand_i','cand_ui',
              'offsets','link_ua','common','y')

def candidate_signature(frame):
    fields = ['uid', 'item_id', 'label']
    fields += [key for key in ('retrieval_rank', 'itemknn_score',
                               'decaypop_score', 'retrieval_source') if key in frame]
    values = pd.util.hash_pandas_object(frame[fields], index=False).to_numpy(dtype=np.uint64)
    return hashlib.sha256(values.tobytes()).hexdigest()

def store_metadata(frame, history_end):
    return dict(version=STORE_VERSION, history_end=int(history_end), seed=SEED,
                n_users=N_USERS, n_items=N_ITEMS, n_rows=len(frame),
                candidate_hash=candidate_signature(frame),
                edges_hash=hashlib.sha256(FINE_EDGES.tobytes()).hexdigest(),
                history_bytes=(DATA/'events_sample.parquet').stat().st_size,
                artists_hash=hashlib.sha256(ART.tobytes()).hexdigest())

def store_ready(name, frame, history_end):
    folder = LOCAL / f'store_{name}'
    try:
        if not (folder/'ready.txt').exists():
            return False
        if json.loads((folder/'manifest.json').read_text()) != store_metadata(frame, history_end):
            return False
        if any(not (folder/f'{key}.npy').is_file() for key in STORE_KEYS):
            return False
        y = np.load(folder/'y.npy', mmap_mode='r')
        return len(y) == len(frame) and y.dtype == np.uint8
    except (OSError, ValueError, KeyError, json.JSONDecodeError):
        return False




def candidate_arrays(frame):
    u = pd.Index(users).get_indexer(frame.uid).astype(np.int32)
    raw = frame.item_id.to_numpy(dtype=np.uint32)
    it = np.searchsorted(items, raw).astype(np.int32)

    pair_keys = (u.astype(np.uint64) << np.uint64(32)) | raw.astype(np.uint64)
    ui_keys, inv_ui = np.unique(pair_keys, return_inverse=True)

    counts = APTR[it + 1] - APTR[it]
    offsets = np.r_[0, np.cumsum(counts, dtype=np.int64)]
    nlinks = int(offsets[-1])

    link_rows = np.repeat(np.arange(len(frame), dtype=np.int32), counts)
    within = np.arange(nlinks, dtype=np.int64) - np.repeat(offsets[:-1], counts)
    art_links = ART[APTR[it[link_rows]] + within]

    ua_per_link = (u[link_rows].astype(np.uint64) << np.uint64(32)) | art_links.astype(np.uint64)
    ua_keys, inv_ua = np.unique(ua_per_link, return_inverse=True)

    if 'retrieval_rank' in frame:
        common = np.column_stack([
            frame.retrieval_rank.to_numpy(dtype=np.float32),
            frame.itemknn_score.to_numpy(dtype=np.float32),
            frame.decaypop_score.to_numpy(dtype=np.float32),
            frame.retrieval_source.eq('itemknn').to_numpy(dtype=np.float32)
        ])
    else:
        common = np.zeros((len(frame), 4), np.float32)

    return dict(
        u=u, it=it,
        y=frame.label.to_numpy(dtype=np.uint8),
        common=common,
        ui_keys=ui_keys,
        inv_ui=inv_ui,
        ua_keys=ua_keys,
        offsets=offsets,
        inv_ua=inv_ua.astype(np.int32)
    )


def load_main_candidates(split):
    c = pd.read_parquet(
        DATA / 'candidates.parquet',
        filters=[('split', '==', split)]
    )
    return c.sort_values(
        ['group_id', 'retrieval_rank'],
        kind='stable'
    ).reset_index(drop=True)


def create_store(name, frame, history_end):

    start = time.perf_counter()
    end = int(history_end)
    n = np.searchsorted(ET, end, side='left')
    x = candidate_arrays(frame)

    available = psutil.virtual_memory().available
    budget = int(min(RAM_MAX_GIB * 1024**3, available * RAM_SHARE))

    bytes_per_row = NF * N_CHANNELS * np.dtype(np.float32).itemsize
    all_rows = N_USERS + N_ITEMS + len(x['ui_keys']) + len(x['ua_keys']) + 2
    direct = all_rows * bytes_per_row < budget * 0.88

    t = time.perf_counter()

    if direct:
        map_ui = np.arange(1, len(x['ui_keys']) + 1, dtype=np.int32)
        map_ua = np.arange(1, len(x['ua_keys']) + 1, dtype=np.int32)
        n_ui, n_ua = len(map_ui), len(map_ua)

        print(f'{name}: direct candidate mapping; no mark_relations pass', flush=True)
    else:
        seen_ui, seen_ua = mark_relations(
            EU[:n], EI_RAW[:n], EI[:n], APTR, ART,
            x['ui_keys'], x['ua_keys']
        )
        map_ui = np.cumsum(seen_ui, dtype=np.int32) * seen_ui
        map_ua = np.cumsum(seen_ua, dtype=np.int32) * seen_ua
        n_ui, n_ua = int(seen_ui.sum()), int(seen_ua.sum())

        del seen_ui, seen_ua
        print(f'{name}: compact observed mapping', flush=True)

    uiref = map_ui[x['inv_ui']]
    link_ua = map_ua[x['inv_ua']]

    print(
        f'{name}: indexing {time.perf_counter()-t:.1f}s, '
        f'events={n:,}, ui={n_ui:,}, ua={n_ua:,}',
        flush=True
    )

    d = LOCAL / f'store_{name}'
    d.mkdir(parents=True, exist_ok=True)

    ram_used = 0
    if name == 'test':
        needed = (N_USERS + N_ITEMS + n_ui + 1) * NF * N_CHANNELS * 4
        if budget < needed:
            raise MemoryError(f'Test requires at least {needed / 2**30:.2f} GiB staging; budget {budget / 2**30:.2f} GiB')

    def tmp(k, shape):
        nonlocal ram_used

        nb = int(np.prod(shape, dtype=np.int64)) * 4

        if ram_used + nb <= budget:
            ram_used += nb
            return np.zeros(shape, dtype=np.float32)

        return np.lib.format.open_memmap(
            d / f'raw_{k}.npy',
            mode='w+',
            dtype=np.float32,
            shape=shape
        )

    U = tmp('u', (N_USERS, NF, N_CHANNELS))
    I = tmp('i', (N_ITEMS, NF, N_CHANNELS))
    UI = tmp('ui', (n_ui + 1, NF, N_CHANNELS))
    UA = tmp('ua', (n_ua + 1, NF, N_CHANNELS))

    print(
        f'{name}: RAM staging {ram_used/2**30:.2f} GiB / '
        f'budget {budget/2**30:.2f} GiB',
        flush=True
    )

    last_u = np.full(N_USERS, -1, np.int64)
    last_i = np.full(N_ITEMS, -1, np.int64)
    last_ui = np.full(n_ui + 1, -1, np.int64)
    first_ui = np.full(n_ui + 1, -1, np.int64)
    last_ratio = np.zeros(n_ui + 1, np.float32)
    like = np.zeros(n_ui + 1, np.float32)
    dislike = np.zeros(n_ui + 1, np.float32)
    last_ua = np.full(n_ua + 1, -1, np.int64)

    t = time.perf_counter()

    aggregate_history_into(
        U, I, UI, UA,
        last_u, last_i, last_ui, first_ui,
        last_ratio, like, dislike, last_ua,
        EU[:n], EI_RAW[:n], EI[:n], ET[:n],
        EK[:n], ER[:n], EO[:n], EL[:n],
        end, FINE_EDGES, APTR, ART,
        x['ui_keys'], x['ua_keys'], map_ui, map_ua
    )

    for a in (U, I, UI, UA):
        if isinstance(a, np.memmap):
            a.flush()

    print(
        f'{name}: event aggregation {time.perf_counter()-t:.1f}s',
        flush=True
    )

    if direct:
        uiref = np.where(last_ui[uiref] >= 0, uiref, 0).astype(np.int32)
        link_ua = np.where(last_ua[link_ua] >= 0, link_ua, 0).astype(np.int32)

    t = time.perf_counter()

    save_dense_bins(d, 'u', U)
    save_dense_bins(d, 'i', I)
    save_sparse_bins(d, 'ui', UI)
    save_sparse_bins(d, 'ua', UA)

    del U, I, UI, UA
    gc.collect()

    for k in ('u', 'i', 'ui', 'ua'):
        p = d / f'raw_{k}.npy'
        if p.exists():
            p.unlink()

    print(
        f'{name}: save and compression {time.perf_counter()-t:.1f}s',
        flush=True
    )

    ui_meta = np.column_stack([
        np.where(last_ui >= 0, np.log1p(np.maximum(0, end-last_ui)/DAY), 0),
        np.where(first_ui >= 0, np.log1p(np.maximum(0, end-first_ui)/DAY), 0),
        last_ratio,
        like,
        dislike,
        (last_ui >= 0).astype(np.float32)
    ]).astype(np.float32)

    arrays = dict(
        u_last=np.where(
            last_u >= 0, np.log1p(np.maximum(0, end-last_u)/DAY), 0
        ).astype(np.float32),
        i_last=np.where(
            last_i >= 0, np.log1p(np.maximum(0, end-last_i)/DAY), 0
        ).astype(np.float32),
        ua_last=np.where(
            last_ua >= 0, np.log1p(np.maximum(0, end-last_ua)/DAY), 0
        ).astype(np.float32),
        ui_meta=ui_meta,
        cand_u=x['u'],
        cand_i=x['it'],
        cand_ui=uiref,
        offsets=x['offsets'],
        link_ua=link_ua,
        y=x['y'],
        common=x['common']
    )

    for k, v in arrays.items():
        np.save(d / f'{k}.npy', v)

    (d / 'manifest.json').write_text(json.dumps(store_metadata(frame, end), indent=2))
    (d / 'ready.txt').write_text(
        f'v3_sparse_fast; history_end={end}; '
        f'count={n}; secs={time.perf_counter()-start:.1f}'
    )

    print(
        name,
        'history events', f'{n:,}',
        'pairs', f'{len(frame):,}',
        'stored ui', f'{n_ui:,}',
        'stored ua', f'{n_ua:,}',
        'seconds', round(time.perf_counter()-start, 1),
        flush=True
    )

    del arrays, x, ui_meta
    gc.collect()



for day in hist_days.itertuples(index=False):
    d = LOCAL / f'store_{day.name}'
    frame = historical_candidates(int(day.cutoff), SEED + int(day.name.split('_')[1]))
    if not store_ready(day.name, frame, int(day.history_end)):
        shutil.rmtree(d, ignore_errors=True)
        create_store(day.name, frame, int(day.history_end))
    del frame
    gc.collect()

for split in ('train', 'valid'):
    d = LOCAL / f'store_{split}'
    frame = load_main_candidates(split)
    if not store_ready(split, frame, int(snaps.loc[split].history_end)):
        shutil.rmtree(d, ignore_errors=True)
        create_store(split, frame, int(snaps.loc[split].history_end))
    del frame
    gc.collect()

hist_0: direct candidate mapping; no mark_relations pass
hist_0: indexing 0.0s, events=44,944,840, ui=321,513, ua=292,877
hist_0: RAM staging 1.39 GiB / budget 3.00 GiB
hist_0: event aggregation 29.4s
  ui: 321,514 rows, 495,168 nonempty time bins
  ua: 292,878 rows, 794,683 nonempty time bins
hist_0: save and compression 7.4s
hist_0 history events 44,944,840 pairs 394,004 stored ui 321,513 stored ua 292,877 seconds 37.1
hist_1: direct candidate mapping; no mark_relations pass
hist_1: indexing 0.0s, events=45,171,606, ui=299,819, ua=273,944
hist_1: RAM staging 1.36 GiB / budget 3.00 GiB
hist_1: event aggregation 25.7s
  ui: 299,820 rows, 469,313 nonempty time bins
  ua: 273,945 rows, 747,991 nonempty time bins
hist_1: save and compression 8.7s
hist_1 history events 45,171,606 pairs 367,614 stored ui 299,819 stored ua 273,944 seconds 34.7
hist_2: direct candidate mapping; no mark_relations pass
hist_2: indexing 0.0s, events=45,380,992, ui=320,861, ua=292,702
hist_2: RAM staging 1.39 GiB / budget 3.00 GiB
hist_2: event aggregation 25.3s
  ui: 320,862 rows, 506,018 nonempty time bins
  ua: 292,703 rows, 806,822 nonempty time bins
hist_2: save and compression 8.1s
hist_2 history events 45,380,992 pairs 392,808 stored ui 320,861 stored ua 292,702 seconds 33.6
hist_3: direct candidate mapping; no mark_relations pass
hist_3: indexing 0.0s, events=45,592,903, ui=325,208, ua=296,605
hist_3: RAM staging 1.40 GiB / budget 3.00 GiB
hist_3: event aggregation 25.9s
  ui: 325,209 rows, 515,971 nonempty time bins
  ua: 296,606 rows, 830,608 nonempty time bins
hist_3: save and compression 9.0s
hist_3 history events 45,592,903 pairs 398,034 stored ui 325,208 stored ua 296,605 seconds 35.1
hist_4: direct candidate mapping; no mark_relations pass
hist_4: indexing 0.0s, events=45,809,680, ui=329,480, ua=301,279
hist_4: RAM staging 1.41 GiB / budget 3.00 GiB
hist_4: event aggregation 25.9s
  ui: 329,481 rows, 520,897 nonempty time bins
  ua: 301,280 rows, 841,964 nonempty time bins
hist_4: save and compression 7.6s
hist_4 history events 45,809,680 pairs 403,598 stored ui 329,480 stored ua 301,279 seconds 33.7
hist_5: direct candidate mapping; no mark_relations pass
hist_5: indexing 0.0s, events=46,040,288, ui=310,974, ua=284,180
hist_5: RAM staging 1.38 GiB / budget 3.00 GiB
hist_5: event aggregation 25.9s
  ui: 310,975 rows, 486,866 nonempty time bins
  ua: 284,181 rows, 785,829 nonempty time bins
hist_5: save and compression 4.2s
hist_5 history events 46,040,288 pairs 380,952 stored ui 310,974 stored ua 284,180 seconds 30.3
hist_6: direct candidate mapping; no mark_relations pass
hist_6: indexing 0.0s, events=46,258,237, ui=309,373, ua=282,843
hist_6: RAM staging 1.37 GiB / budget 3.00 GiB
hist_6: event aggregation 27.1s
  ui: 309,374 rows, 482,293 nonempty time bins
  ua: 282,844 rows, 784,652 nonempty time bins
hist_6: save and compression 9.2s
hist_6 history events 46,258,237 pairs 378,365 stored ui 309,373 stored ua 282,843 seconds 36.5
hist_7: direct candidate mapping; no mark_relations pass
hist_7: indexing 0.0s, events=46,472,811, ui=302,894, ua=276,570
hist_7: RAM staging 1.36 GiB / budget 3.00 GiB
hist_7: event aggregation 26.7s
  ui: 302,895 rows, 472,073 nonempty time bins
  ua: 276,571 rows, 757,451 nonempty time bins
hist_7: save and compression 10.9s
hist_7 history events 46,472,811 pairs 370,942 stored ui 302,894 stored ua 276,570 seconds 37.8
hist_8: direct candidate mapping; no mark_relations pass
hist_8: indexing 0.0s, events=46,680,663, ui=292,718, ua=267,298
hist_8: RAM staging 1.34 GiB / budget 3.00 GiB
hist_8: event aggregation 27.3s
  ui: 292,719 rows, 461,674 nonempty time bins
  ua: 267,299 rows, 740,200 nonempty time bins
hist_8: save and compression 8.9s
hist_8 history events 46,680,663 pairs 358,202 stored ui 292,718 stored ua 267,298 seconds 36.4
hist_9: direct candidate mapping; no mark_relations pass
hist_9: indexing 0.0s, events=46,873,123, ui=329,479, ua=301,277
hist_9: RAM staging 1.41 GiB / budget 3.00 GiB
hist_9: event aggregation 27.4s
  ui: 329,480 rows, 526,707 nonempty time bins
  ua: 301,278 rows, 845,488 nonempty time bins
hist_9: save and compression 8.7s
hist_9 history events 46,873,123 pairs 403,871 stored ui 329,479 stored ua 301,277 seconds 36.3
train: compact observed mapping
train: indexing 26.7s, events=47,098,526, ui=2,271,681, ua=1,442,175
train: RAM staging 2.88 GiB / budget 3.00 GiB
train: event aggregation 717.4s
  ui: 2,271,682 rows, 5,615,117 nonempty time bins
  ua: 1,442,176 rows, 5,167,220 nonempty time bins
train: save and compression 22.1s
train history events 47,098,526 pairs 6,000,000 stored ui 2,271,681 stored ua 1,442,175 seconds 770.4
valid: compact observed mapping
valid: indexing 26.5s, events=47,324,518, ui=2,278,646, ua=1,446,175
valid: RAM staging 2.88 GiB / budget 3.00 GiB
valid: event aggregation 724.2s
  ui: 2,278,647 rows, 5,642,462 nonempty time bins
  ua: 1,446,176 rows, 5,189,005 nonempty time bins
valid: save and compression 23.8s
valid history events 47,324,518 pairs 6,000,000 stored ui 2,278,646 stored ua 1,446,175 seconds 778.9

## Энкодер

In [27]:
class RelationStore:
    def __init__(self,name):
        d=LOCAL/f'store_{name}'
        keys=('u','i','ui_ptr','ui_bin','ui_val','ua_ptr','ua_bin','ua_val',
              'u_last','i_last','ua_last','ui_meta',
              'cand_u','cand_i','cand_ui','offsets','link_ua','common','y')
        self.a={k:np.load(d/f'{k}.npy',mmap_mode='r') for k in keys}
        self.n=len(self.a['y'])

    def batch(self,rows):
        a=self.a
        rows=np.asarray(rows,dtype=np.int64)
        uu=a['cand_u'][rows]
        ii=a['cand_i'][rows]
        pp=a['cand_ui'][rows]
        parts=[np.asarray(a['u'][uu],dtype=np.float32),
               np.asarray(a['i'][ii],dtype=np.float32),
               gather_sparse_bins(a['ui_ptr'],a['ui_bin'],a['ui_val'],pp,NF,N_CHANNELS)]
        lengths=a['offsets'][rows+1]-a['offsets'][rows]
        start=a['offsets'][rows]
        within=np.arange(int(lengths.sum()))-np.repeat(np.cumsum(lengths)-lengths,lengths)
        indices=a['link_ua'][np.repeat(start,lengths)+within]
        ua_sum=np.zeros((len(rows),NF,N_CHANNELS),np.float32)
        ua_max=np.zeros_like(ua_sum)
        artist_age=np.zeros(len(rows),np.float32)
        n_known=np.zeros(len(rows),np.float32)
        if len(indices):
            vals=np.expm1(gather_sparse_bins(a['ua_ptr'],a['ua_bin'],a['ua_val'],
                                        indices,NF,N_CHANNELS))
            nonempty=np.flatnonzero(lengths>0)
            starts=np.r_[0,np.cumsum(lengths)][nonempty]
            ua_sum[nonempty]=np.log1p(np.add.reduceat(vals,starts,axis=0))
            ua_max[nonempty]=np.log1p(np.maximum.reduceat(vals,starts,axis=0))
            known=(indices>0)
            ages=np.where(known,np.asarray(a['ua_last'][indices]),np.inf)
            artist_age[nonempty]=np.minimum.reduceat(ages,starts)
            n_known[nonempty]=np.add.reduceat(known.astype(np.float32),starts)
            artist_age[~np.isfinite(artist_age)]=0
        parts.extend([ua_sum,ua_max])
        side=np.column_stack([a['ui_meta'][pp],a['u_last'][uu],a['i_last'][ii],
            np.log1p(lengths.astype(np.float32)),artist_age,np.log1p(n_known)]).astype(np.float32)
        return np.stack(parts,axis=1),side


def torch_batch(store,rows):
    history,side=store.batch(rows)
    return (torch.from_numpy(history).to(DEVICE),
            torch.from_numpy(side).to(DEVICE))

class AdaptiveBinsEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.boundary_logits=nn.Parameter(torch.zeros(5,N_COARSE))
        self.register_buffer('fine_centers',torch.tensor(FINE_CENTERS))
        self.temperature=.22
        width=N_COARSE*N_CHANNELS+N_CHANNELS
        self.parts=nn.ModuleList([nn.Sequential(nn.Linear(width,48),nn.GELU(),
                            nn.Linear(48,48),nn.GELU()) for _ in range(5)])
        self.fuse=nn.Sequential(nn.Linear(48*8+11,160),nn.GELU(),
                   nn.LayerNorm(160),nn.Linear(160,Z_DIM),nn.GELU())
        self.head=nn.Sequential(nn.Linear(Z_DIM,64),nn.GELU(),nn.Linear(64,1))

    def soft_bins(self):

        widths=.95*torch.softmax(self.boundary_logits,dim=-1)+.05/N_COARSE
        x0,x1=0.,float(np.log1p(365))
        bounds=x0+(x1-x0)*torch.cumsum(widths,dim=-1)[:,:-1]
        cdf=torch.sigmoid((self.fine_centers[None,:,None]-bounds[:,None,:])/self.temperature)
        membership=torch.cat([1-cdf[:,:,:1],cdf[:,:,:-1]-cdf[:,:,1:],cdf[:,:,-1:]],dim=-1)
        return membership,bounds

    def forward(self,mem,side):

        hist=torch.expm1(mem.clamp(min=0))
        weights,_=self.soft_bins()
        pooled=torch.einsum('brfc,rfk->brkc',hist,weights)
        absolute=torch.log1p(hist.sum(dim=2))
        dense=torch.cat([torch.log1p(pooled).flatten(2),absolute],dim=-1)
        p=[layer(dense[:,j]) for j,layer in enumerate(self.parts)]
        u,it,ui,ua,ua_max=p
        z=self.fuse(torch.cat([*p,u*it,u*ua,ui*ua,side],dim=-1))
        return self.head(z).squeeze(-1),z

train_store=RelationStore('train')
valid_store=RelationStore('valid')
model=AdaptiveBinsEncoder().to(DEVICE)
print('Encoder parameters:',sum(p.numel() for p in model.parameters()))
print('Initial learned boundaries in days:')
with torch.no_grad():
    print(np.expm1(model.soft_bins()[1].cpu().numpy()).round(2))

Encoder parameters: 107039
Initial learned boundaries in days:
[[  1.67   6.15  18.13  50.17 135.85]
 [  1.67   6.15  18.13  50.17 135.85]
 [  1.67   6.15  18.13  50.17 135.85]
 [  1.67   6.15  18.13  50.17 135.85]
 [  1.67   6.15  18.13  50.17 135.85]]

## Обучение

In [28]:
def historical_ndcg(scores,n_neg):
    s=scores.reshape(-1,n_neg+1)
    rank=(s[:,1:]>s[:,:1]).sum(axis=1)
    k=min(10,n_neg+1)
    return np.where(rank<k,1/np.log2(rank+2),0.).mean()

@torch.no_grad()
def predict_net(net,store,rows,batch_size=INFER_BATCH,features=False):
    net.eval()
    arr=np.empty((len(rows),Z_DIM+1) if features else len(rows),np.float32)
    for left in range(0,len(rows),batch_size):
        rr=np.asarray(rows[left:left+batch_size],dtype=np.int64)
        score,z=net(*torch_batch(store,rr))
        n=len(rr)
        if features:
            arr[left:left+n,:Z_DIM]=z.cpu().numpy()
            arr[left:left+n,-1]=score.cpu().numpy()
        else:
            arr[left:left+n]=score.cpu().numpy()
    return arr

def historical_eval(net,store,max_groups=4000):
    groups=min(store.n//(NEG+1),max_groups)
    group_ids=np.linspace(0,store.n//(NEG+1)-1,groups,dtype=np.int64)
    rr=(group_ids[:,None]*(NEG+1)+np.arange(NEG+1)).ravel()
    s=predict_net(net,store,rr)
    return historical_ndcg(s,NEG)

hist_train_names=hist_days.name.iloc[:-1].tolist()
hist_dev=RelationStore(hist_days.name.iloc[-1])
encoder=AdaptiveBinsEncoder().to(DEVICE)
opt=torch.optim.AdamW(encoder.parameters(),lr=ENC_LR,weight_decay=1e-3)
logs=[]
best=-1.
bad_epochs=0
for epoch in range(ENC_EPOCHS):
    encoder.train()
    losses=[]
    shuffled=rng.permutation(hist_train_names)
    for name in shuffled:
        st=RelationStore(name)
        n_groups=st.n//(NEG+1)
        order=rng.permutation(n_groups)
        for left in tqdm(range(0,n_groups,BATCH_GROUPS),desc=f'epoch {epoch+1}: {name}',leave=False):
            batch_ids=order[left:left+BATCH_GROUPS]
            rows=(batch_ids[:,None]*(NEG+1)+np.arange(NEG+1)).ravel()
            scores,_=encoder(*torch_batch(st,rows))
            loss=F.cross_entropy(scores.reshape(len(batch_ids),NEG+1),
                     torch.zeros(len(batch_ids),device=DEVICE,dtype=torch.long))
            opt.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(encoder.parameters(),1.)
            opt.step()
            losses.append(float(loss.item()))
        del st
    score=historical_eval(encoder,hist_dev)
    entry=dict(epoch=epoch+1,train_loss=float(np.mean(losses)),hist_dev_ndcg10=float(score))
    logs.append(entry)
    print('Epoch',epoch+1,'loss',round(entry['train_loss'],4),
          'historical dev NDCG@10',round(score,5),flush=True)
    if score>best+1e-5:
        best=score
        bad_epochs=0
        torch.save(encoder.state_dict(),OUT/'encoder.pt')
    else:
        bad_epochs+=1
        if bad_epochs>=ENC_PATIENCE:
            print('Historical early stopping')
            break
pd.DataFrame(logs).to_csv(OUT/'encoder_training.csv',index=False)
encoder.load_state_dict(torch.load(OUT/'encoder.pt',map_location=DEVICE,weights_only=True))
encoder.eval()
with torch.no_grad():
    boundaries=np.expm1(encoder.soft_bins()[1].cpu().numpy())
pd.DataFrame(boundaries,index=['user','item','user_item','user_artist_sum','user_artist_max'],
    columns=[f'cut_{j+1}_days' for j in range(N_COARSE-1)]).to_csv(OUT/'learned_boundaries.csv')
print('Learned boundaries (days):')
display(pd.read_csv(OUT/'learned_boundaries.csv'))

epoch 1: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 1: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 1: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 1: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 1: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 1: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 1: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

epoch 1: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 1: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

Epoch 1 loss 1.157 historical dev NDCG@10 0.8342

epoch 2: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 2: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 2: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 2: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

epoch 2: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 2: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 2: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 2: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 2: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

Epoch 2 loss 1.0426 historical dev NDCG@10 0.83799

epoch 3: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 3: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 3: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 3: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 3: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 3: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 3: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 3: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 3: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

Epoch 3 loss 1.0232 historical dev NDCG@10 0.83627

epoch 4: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 4: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 4: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 4: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 4: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 4: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 4: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 4: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 4: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

Epoch 4 loss 1.0107 historical dev NDCG@10 0.83816

epoch 5: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 5: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 5: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 5: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 5: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 5: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 5: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

epoch 5: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 5: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

Epoch 5 loss 1.0004 historical dev NDCG@10 0.84296

epoch 6: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 6: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 6: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 6: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 6: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 6: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 6: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 6: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 6: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

Epoch 6 loss 0.9914 historical dev NDCG@10 0.83628

epoch 7: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 7: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 7: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 7: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 7: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 7: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

epoch 7: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 7: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 7: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

Epoch 7 loss 0.9847 historical dev NDCG@10 0.84096

epoch 8: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 8: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 8: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 8: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 8: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 8: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 8: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 8: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 8: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

Epoch 8 loss 0.9777 historical dev NDCG@10 0.84403

epoch 9: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

epoch 9: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 9: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 9: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 9: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 9: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 9: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 9: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 9: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

Epoch 9 loss 0.9721 historical dev NDCG@10 0.84386

epoch 10: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

epoch 10: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 10: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 10: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 10: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 10: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 10: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 10: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 10: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

Epoch 10 loss 0.9662 historical dev NDCG@10 0.84332

epoch 11: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 11: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 11: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 11: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 11: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 11: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 11: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 11: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 11: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

Epoch 11 loss 0.9611 historical dev NDCG@10 0.84564

epoch 12: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 12: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 12: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 12: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 12: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 12: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 12: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 12: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 12: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

Epoch 12 loss 0.9565 historical dev NDCG@10 0.84655

epoch 13: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 13: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 13: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 13: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 13: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 13: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 13: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

epoch 13: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 13: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

Epoch 13 loss 0.9514 historical dev NDCG@10 0.8436

epoch 14: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 14: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

epoch 14: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 14: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 14: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 14: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 14: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 14: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 14: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

Epoch 14 loss 0.9463 historical dev NDCG@10 0.84408

epoch 15: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 15: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 15: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

epoch 15: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 15: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 15: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 15: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 15: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 15: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

Epoch 15 loss 0.9417 historical dev NDCG@10 0.84305

epoch 16: hist_4:   0%|          | 0/81 [00:00<?, ?it/s]

epoch 16: hist_3:   0%|          | 0/80 [00:00<?, ?it/s]

epoch 16: hist_8:   0%|          | 0/72 [00:00<?, ?it/s]

epoch 16: hist_5:   0%|          | 0/77 [00:00<?, ?it/s]

epoch 16: hist_7:   0%|          | 0/75 [00:00<?, ?it/s]

epoch 16: hist_1:   0%|          | 0/74 [00:00<?, ?it/s]

epoch 16: hist_0:   0%|          | 0/79 [00:00<?, ?it/s]

epoch 16: hist_6:   0%|          | 0/76 [00:00<?, ?it/s]

epoch 16: hist_2:   0%|          | 0/79 [00:00<?, ?it/s]

Epoch 16 loss 0.9372 historical dev NDCG@10 0.83993
Historical early stopping
Learned boundaries (days):

        Unnamed: 0  cut_1_days  cut_2_days  cut_3_days  cut_4_days  cut_5_days
0             user    1.099249    3.582718   11.229781   36.699060  120.501870
1             item    1.635267    6.579147   17.444391   46.460210  125.060196
2        user_item    1.378970    4.840265   14.960426   43.024284  123.473680
3  user_artist_sum    1.316656    5.335434   16.372677   45.149190  130.136950
4  user_artist_max    1.645998    6.695809   18.047964   53.278385  148.670930

## Признаки

In [29]:
def checkpoint_hash(file):
    checksum = hashlib.sha256()
    with open(file, 'rb') as source:
        for data in iter(lambda: source.read(1 << 20), b''):
            checksum.update(data)
    return checksum.hexdigest()

def feature_token(file, shape, checkpoint, split):
    return dict(shape=list(shape), dtype='float16',
                checkpoint=checkpoint_hash(checkpoint),
                history_end=int(snaps.loc[split].history_end),
                file_bytes=file.stat().st_size)

def feature_ready(file, shape, checkpoint, split):
    marker = file.with_suffix(file.suffix + '.done.json')
    try:
        if not marker.exists() or not file.exists():
            return False
        meta = json.loads(marker.read_text())
        arr = np.load(file, mmap_mode='r')
        return (arr.shape == tuple(shape) and arr.dtype == np.float16
                and meta == feature_token(file, shape, checkpoint, split))
    except (OSError, ValueError, KeyError, json.JSONDecodeError):
        return False

def finish_feature(tmp, filename, shape, checkpoint, split):
    os.replace(tmp, filename)
    marker = filename.with_suffix(filename.suffix + '.done.json')
    staged = marker.with_suffix('.partial.json')
    staged.write_text(json.dumps(feature_token(filename, shape, checkpoint, split), indent=2))
    os.replace(staged, marker)

def extract_features(name, store):
    filename = LOCAL / f'learned_{name}.npy'
    tmp = LOCAL / f'learned_{name}.partial.npy'
    shape = (store.n, Z_DIM + 1)
    result = np.lib.format.open_memmap(tmp, mode='w+', dtype=np.float16, shape=shape)
    for left in tqdm(range(0, store.n, INFER_BATCH), desc=f'Extract {name}'):
        right = min(store.n, left + INFER_BATCH)
        result[left:right] = predict_net(encoder, store, np.arange(left, right), features=True)
    result.flush()
    del result
    finish_feature(tmp, filename, shape, OUT/'encoder.pt', name)
    print(name, 'features:', store.n, 'rows')

extract_features('train', train_store)
extract_features('valid', valid_store)
shutil.copy2(LOCAL/'learned_train.npy', OUT/'learned_train.npy')
shutil.copy2(LOCAL/'learned_valid.npy', OUT/'learned_valid.npy')

Extract train:   0%|          | 0/1465 [00:00<?, ?it/s]

train features: 6000000 rows

Extract valid:   0%|          | 0/1465 [00:00<?, ?it/s]

valid features: 6000000 rows

PosixPath('/content/drive/MyDrive/TLab_Yambda/adaptive_bins_autofe_sparse_v3/learned_valid.npy')

## CatBoost

In [30]:
cb_y=np.asarray(train_store.a['y']).reshape(N_USERS,C)
negative=[]
neg_rng=np.random.default_rng(SEED)
for u in range(N_USERS):
    choices=np.flatnonzero(cb_y[u]==0)
    negative.append(u*C+neg_rng.choice(choices,size=min(CB_NEG_PER_USER,len(choices)),replace=False))
cb_rows=np.sort(np.r_[np.flatnonzero(cb_y.ravel()),np.concatenate(negative)]).astype(np.int64)
valid_users=np.sort(np.random.default_rng(SEED).choice(N_USERS,
                            size=min(CB_EVAL_USERS,N_USERS),replace=False))
valid_rows=(valid_users[:,None]*C+np.arange(C)).ravel()
print('Matched train rows:',len(cb_rows),'Validation early stopping rows:',len(valid_rows))

feature_sets=json.loads((R2/'feature_sets.json').read_text())
manual_cols=feature_sets['R2']
raw_common=['retrieval_rank','itemknn_score','decaypop_score','source_is_itemknn']
learned_cols=[f'latent_{j:02d}' for j in range(Z_DIM)]+['neural_score']

def load_manual(split,rows):
    f=R2/'features'/f'features_{split}.parquet'
    wanted=list(dict.fromkeys(manual_cols+['label']))
    rows=np.asarray(rows,dtype=np.int64)
    pf=pq.ParquetFile(f)
    chunks=[]
    offset=0
    for b in pf.iter_batches(batch_size=100_000,columns=wanted):
        stop=offset+b.num_rows
        lo=np.searchsorted(rows,offset)
        hi=np.searchsorted(rows,stop)
        if lo<hi:
            chunks.append(b.to_pandas().iloc[rows[lo:hi]-offset])
        offset=stop
    return pd.concat(chunks,ignore_index=True)

man_train=load_manual('train',cb_rows)
man_eval=load_manual('valid',valid_rows)
mem_train=np.load(LOCAL/'learned_train.npy',mmap_mode='r')
mem_valid=np.load(LOCAL/'learned_valid.npy',mmap_mode='r')
manual_tr=man_train[manual_cols].to_numpy(dtype=np.float32)
manual_va=man_eval[manual_cols].to_numpy(dtype=np.float32)
learned_tr=np.column_stack([mem_train[cb_rows].astype(np.float32),
                  np.asarray(train_store.a['common'][cb_rows],dtype=np.float32)])
learned_va=np.column_stack([mem_valid[valid_rows].astype(np.float32),
                  np.asarray(valid_store.a['common'][valid_rows],dtype=np.float32)])
y_train=np.asarray(train_store.a['y'][cb_rows],dtype=np.int8)
y_valid=np.asarray(valid_store.a['y'][valid_rows],dtype=np.int8)

def fit_catboost(name,X_train,X_valid):
    model=CatBoostClassifier(iterations=CB_TREES,depth=CB_DEPTH,learning_rate=CB_LR,
        loss_function='Logloss',eval_metric='Logloss',random_seed=SEED,
        task_type='GPU' if DEVICE=='cuda' else 'CPU',verbose=200)
    print(name,X_train.shape,X_valid.shape)
    model.fit(X_train,y_train,eval_set=(X_valid,y_valid),early_stopping_rounds=120)
    model.save_model(str(OUT/f'{name}.cbm'))
    return model

manual=fit_catboost('R2_matched',manual_tr,manual_va)
automatic=fit_catboost('A1_adaptive',learned_tr,learned_va)
del manual_tr,manual_va,learned_tr,learned_va,man_train,man_eval
gc.collect()

def assert_alignment(split, store):
    cols = ['uid', 'item_id', 'group_id', 'retrieval_rank']
    stream = pq.ParquetFile(R2/'features'/f'features_{split}.parquet')
    offset = 0
    for batch in stream.iter_batches(batch_size=100_000, columns=cols):
        d = batch.to_pandas()
        r = slice(offset, offset + len(d))
        u = np.asarray(store.a['cand_u'][r], dtype=np.intp)
        i = np.asarray(store.a['cand_i'][r], dtype=np.intp)
        rank = np.asarray(store.a['common'][r, 0], dtype=np.int32)
        group = int(snaps.loc[split].snapshot_id) * N_USERS + u
        if not (np.array_equal(d.uid.to_numpy(), users[u])
                and np.array_equal(d.item_id.to_numpy(), items[i])
                and np.array_equal(d.group_id.to_numpy(), group)
                and np.array_equal(d.retrieval_rank.to_numpy(), rank)):
            raise ValueError(f'Candidate order mismatch: {split}, row {offset}')
        offset += len(d)
    assert offset == store.n, f'Candidate count mismatch: {split}'

assert_alignment('train', train_store)
assert_alignment('valid', valid_store)

Matched train rows: 1036912 Validation early stopping rows: 307200
R2_matched (1036912, 65) (307200, 65)
0:	learn: 0.5974327	test: 0.5924503	best: 0.5924503 (0)	total: 72ms	remaining: 35.9s
200:	learn: 0.0918739	test: 0.0417417	best: 0.0417417 (200)	total: 12s	remaining: 17.8s
400:	learn: 0.0862927	test: 0.0408453	best: 0.0408453 (400)	total: 23.8s	remaining: 5.88s
499:	learn: 0.0841925	test: 0.0405184	best: 0.0405158 (496)	total: 29.4s	remaining: 0us
bestTest = 0.04051583608
bestIteration = 496
Shrink model to first 497 iterations.
A1_adaptive (1036912, 69) (307200, 69)
0:	learn: 0.5942731	test: 0.5896981	best: 0.5896981 (0)	total: 40.4ms	remaining: 20.2s
200:	learn: 0.0940592	test: 0.0418744	best: 0.0418744 (200)	total: 4.67s	remaining: 6.94s
400:	learn: 0.0900578	test: 0.0415538	best: 0.0415530 (397)	total: 9.12s	remaining: 2.25s
499:	learn: 0.0884865	test: 0.0414419	best: 0.0414419 (499)	total: 11.3s	remaining: 0us
bestTest = 0.04144193331
bestIteration = 499

1962

## Подбор

In [48]:
def future_totals(split):
    s=snaps.loc[split]
    mask=(ET>=int(s.cutoff))&(ET<int(s.end))&(EK==1)
    frame=pd.DataFrame({'u':EU[mask],'item':EI_RAW[mask]}).drop_duplicates()
    return np.bincount(frame.u.to_numpy(dtype=np.int32),minlength=N_USERS)

from sklearn.model_selection import ParameterSampler

params = {
    'depth': [4, 5, 6, 7, 8],
    'learning_rate': [0.03, 0.05, 0.08],
    'l2_leaf_reg': [5, 10, 30]
}
truth_valid = future_totals('valid')

def tune(name, X_train, X_valid, n_trials=10):
    labels = y_valid.reshape(-1, C)
    total = truth_valid[valid_users]
    discount = 1 / np.log2(np.arange(2, 22))
    ideal = np.r_[0, discount.cumsum()]
    results = []

    for p in tqdm(list(ParameterSampler(params, n_iter=n_trials, random_state=SEED)), desc=name):
        model = CatBoostClassifier(
            iterations=2500, loss_function='Logloss',task_type='GPU' if DEVICE=='cuda' else 'CPU',
            random_seed=SEED, verbose=400, **p
        )
        model.fit(X_train, y_train, eval_set=(X_valid, y_valid),
                  early_stopping_rounds=150)

        scores = model.predict_proba(X_valid)[:, 1].reshape(-1, C)
        top = np.argsort(-scores, axis=1)[:, :20]
        dcg = (np.take_along_axis(labels, top, axis=1) * discount).sum(axis=1)
        ndcg = np.mean(np.where(total > 0, dcg / np.maximum(ideal[np.minimum(total, 20)], 1), 0))

        results.append((ndcg, p, model.tree_count_))
        if ndcg == max(r[0] for r in results):
            model.save_model(str(OUT / f'{name}_best.cbm'))

    result = pd.DataFrame(results, columns=['ndcg@20', 'params', 'trees'])
    result.to_csv(OUT / f'{name}_search.csv', index=False)
    return result.sort_values('ndcg@20', ascending=False)

In [24]:
r2_train = load_manual('train', cb_rows)[manual_cols]
r2_valid = load_manual('valid', valid_rows)[manual_cols]

r2_search = tune('R2', r2_train, r2_valid, n_trials=15)
display(r2_search)

R2:   0%|          | 0/15 [00:00<?, ?it/s]

0:	learn: 0.6342988	test: 0.6312651	best: 0.6312651 (0)	total: 41.3ms	remaining: 1m 43s
400:	learn: 0.0909415	test: 0.0413838	best: 0.0413838 (400)	total: 8.77s	remaining: 45.9s
800:	learn: 0.0851968	test: 0.0403444	best: 0.0403428 (799)	total: 17.5s	remaining: 37.1s
1200:	learn: 0.0811203	test: 0.0397223	best: 0.0397216 (1197)	total: 26.1s	remaining: 28.3s
1600:	learn: 0.0779110	test: 0.0392890	best: 0.0392890 (1600)	total: 34.8s	remaining: 19.5s
2000:	learn: 0.0752301	test: 0.0389808	best: 0.0389804 (1995)	total: 43.5s	remaining: 10.9s
2400:	learn: 0.0728266	test: 0.0386981	best: 0.0386959 (2399)	total: 52.4s	remaining: 2.16s
2499:	learn: 0.0722583	test: 0.0386132	best: 0.0386079 (2489)	total: 54.6s	remaining: 0us
bestTest = 0.0386078612
bestIteration = 2489
Shrink model to first 2490 iterations.
0:	learn: 0.6002357	test: 0.5953030	best: 0.5953030 (0)	total: 26.4ms	remaining: 1m 6s
400:	learn: 0.0928962	test: 0.0416681	best: 0.0416681 (400)	total: 6.58s	remaining: 34.4s
800:	learn: 0.0885437	test: 0.0409146	best: 0.0408968 (782)	total: 13.3s	remaining: 28.2s
1200:	learn: 0.0853561	test: 0.0406423	best: 0.0406180 (1175)	total: 19.8s	remaining: 21.4s
1600:	learn: 0.0829340	test: 0.0403830	best: 0.0403824 (1598)	total: 26.3s	remaining: 14.8s
2000:	learn: 0.0809087	test: 0.0401407	best: 0.0401313 (1982)	total: 32.8s	remaining: 8.19s
2400:	learn: 0.0791688	test: 0.0399959	best: 0.0399901 (2389)	total: 39.4s	remaining: 1.62s
2499:	learn: 0.0787794	test: 0.0399370	best: 0.0399342 (2485)	total: 41s	remaining: 0us
bestTest = 0.03993420283
bestIteration = 2485
Shrink model to first 2486 iterations.
0:	learn: 0.5497826	test: 0.5420344	best: 0.5420344 (0)	total: 26.4ms	remaining: 1m 6s
400:	learn: 0.0898811	test: 0.0411005	best: 0.0410903 (396)	total: 6.75s	remaining: 35.3s
800:	learn: 0.0850741	test: 0.0404728	best: 0.0404695 (797)	total: 13.3s	remaining: 28.3s
1200:	learn: 0.0814649	test: 0.0399616	best: 0.0399351 (1175)	total: 19.8s	remaining: 21.4s
1600:	learn: 0.0786794	test: 0.0396441	best: 0.0396441 (1600)	total: 26.4s	remaining: 14.8s
bestTest = 0.03964371045
bestIteration = 1602
Shrink model to first 1603 iterations.
0:	learn: 0.5974467	test: 0.5924648	best: 0.5924648 (0)	total: 38.3ms	remaining: 1m 35s
400:	learn: 0.0877283	test: 0.0408951	best: 0.0408865 (397)	total: 9.05s	remaining: 47.4s
800:	learn: 0.0813286	test: 0.0401547	best: 0.0401516 (799)	total: 18s	remaining: 38.2s
1200:	learn: 0.0768796	test: 0.0395831	best: 0.0395736 (1195)	total: 27s	remaining: 29.2s
1600:	learn: 0.0734327	test: 0.0391833	best: 0.0391833 (1600)	total: 36s	remaining: 20.2s
2000:	learn: 0.0704809	test: 0.0388576	best: 0.0388576 (2000)	total: 45s	remaining: 11.2s
2400:	learn: 0.0678666	test: 0.0386088	best: 0.0386051 (2398)	total: 54s	remaining: 2.23s
2499:	learn: 0.0673049	test: 0.0385645	best: 0.0385634 (2496)	total: 56.3s	remaining: 0us
bestTest = 0.03856343587
bestIteration = 2496
Shrink model to first 2497 iterations.
0:	learn: 0.5471453	test: 0.5392411	best: 0.5392411 (0)	total: 31.7ms	remaining: 1m 19s
400:	learn: 0.0871762	test: 0.0412272	best: 0.0412178 (394)	total: 7.74s	remaining: 40.5s
800:	learn: 0.0810369	test: 0.0404016	best: 0.0404016 (800)	total: 15.3s	remaining: 32.4s
1200:	learn: 0.0767505	test: 0.0398114	best: 0.0397952 (1192)	total: 22.9s	remaining: 24.7s
1600:	learn: 0.0733579	test: 0.0395651	best: 0.0395549 (1599)	total: 30.4s	remaining: 17.1s
2000:	learn: 0.0705205	test: 0.0393667	best: 0.0393611 (1994)	total: 38.1s	remaining: 9.49s
2400:	learn: 0.0680175	test: 0.0391493	best: 0.0391434 (2397)	total: 45.7s	remaining: 1.88s
2499:	learn: 0.0674599	test: 0.0390489	best: 0.0390489 (2499)	total: 47.6s	remaining: 0us
bestTest = 0.03904894193
bestIteration = 2499
0:	learn: 0.5456514	test: 0.5378443	best: 0.5378443 (0)	total: 38ms	remaining: 1m 34s
400:	learn: 0.0823631	test: 0.0400566	best: 0.0400087 (386)	total: 9.03s	remaining: 47.2s
800:	learn: 0.0742979	test: 0.0392471	best: 0.0392420 (799)	total: 18s	remaining: 38.2s
1200:	learn: 0.0688431	test: 0.0389341	best: 0.0389341 (1200)	total: 27s	remaining: 29.2s
1600:	learn: 0.0642786	test: 0.0385637	best: 0.0385637 (1600)	total: 36s	remaining: 20.2s
2000:	learn: 0.0603991	test: 0.0383232	best: 0.0383067 (1995)	total: 45.2s	remaining: 11.3s
2400:	learn: 0.0570840	test: 0.0380422	best: 0.0380321 (2366)	total: 54.3s	remaining: 2.24s
2499:	learn: 0.0562961	test: 0.0379749	best: 0.0379686 (2497)	total: 56.5s	remaining: 0us
bestTest = 0.03796860377
bestIteration = 2497
Shrink model to first 2498 iterations.
0:	learn: 0.6032289	test: 0.5986587	best: 0.5986587 (0)	total: 20ms	remaining: 50.1s
400:	learn: 0.0969715	test: 0.0424848	best: 0.0424830 (399)	total: 5.18s	remaining: 27.1s
800:	learn: 0.0937847	test: 0.0418692	best: 0.0418645 (797)	total: 10.3s	remaining: 21.9s
1200:	learn: 0.0918353	test: 0.0414839	best: 0.0414839 (1200)	total: 15.4s	remaining: 16.6s
1600:	learn: 0.0902657	test: 0.0412954	best: 0.0412838 (1504)	total: 20.5s	remaining: 11.5s
2000:	learn: 0.0889443	test: 0.0410835	best: 0.0410808 (1975)	total: 25.5s	remaining: 6.36s
2400:	learn: 0.0878384	test: 0.0408989	best: 0.0408929 (2396)	total: 30.6s	remaining: 1.26s
2499:	learn: 0.0875938	test: 0.0408864	best: 0.0408827 (2446)	total: 31.9s	remaining: 0us
bestTest = 0.04088269552
bestIteration = 2446
Shrink model to first 2447 iterations.
0:	learn: 0.6370882	test: 0.6343140	best: 0.6343140 (0)	total: 22.2ms	remaining: 55.6s
400:	learn: 0.0972652	test: 0.0426206	best: 0.0426206 (400)	total: 6.01s	remaining: 31.5s
800:	learn: 0.0938741	test: 0.0419179	best: 0.0419075 (781)	total: 11.8s	remaining: 25s
1200:	learn: 0.0917172	test: 0.0415443	best: 0.0415443 (1200)	total: 17.6s	remaining: 19.1s
1600:	learn: 0.0899492	test: 0.0412560	best: 0.0412560 (1600)	total: 23.3s	remaining: 13.1s
2000:	learn: 0.0884849	test: 0.0410239	best: 0.0410057 (1968)	total: 29.1s	remaining: 7.27s
2400:	learn: 0.0872652	test: 0.0407793	best: 0.0407718 (2394)	total: 34.9s	remaining: 1.44s
2499:	learn: 0.0869846	test: 0.0407231	best: 0.0407206 (2496)	total: 36.5s	remaining: 0us
bestTest = 0.040720644
bestIteration = 2496
Shrink model to first 2497 iterations.
0:	learn: 0.5541909	test: 0.5469706	best: 0.5469706 (0)	total: 20.3ms	remaining: 50.7s
400:	learn: 0.0948772	test: 0.0420482	best: 0.0420426 (367)	total: 5.3s	remaining: 27.7s
800:	learn: 0.0915633	test: 0.0414173	best: 0.0414146 (796)	total: 10.3s	remaining: 21.9s
1200:	learn: 0.0893870	test: 0.0409360	best: 0.0409359 (1198)	total: 15.5s	remaining: 16.8s
1600:	learn: 0.0876935	test: 0.0406931	best: 0.0406381 (1495)	total: 20.7s	remaining: 11.6s
bestTest = 0.04063806852
bestIteration = 1495
Shrink model to first 1496 iterations.
0:	learn: 0.6379629	test: 0.6351970	best: 0.6351970 (0)	total: 20.2ms	remaining: 50.5s
400:	learn: 0.0990846	test: 0.0430735	best: 0.0430735 (400)	total: 5.6s	remaining: 29.3s
800:	learn: 0.0961345	test: 0.0424399	best: 0.0424396 (799)	total: 10.8s	remaining: 22.9s
1200:	learn: 0.0943853	test: 0.0420666	best: 0.0420574 (1196)	total: 16s	remaining: 17.3s
1600:	learn: 0.0929636	test: 0.0416623	best: 0.0416608 (1598)	total: 21.2s	remaining: 11.9s
2000:	learn: 0.0917999	test: 0.0414539	best: 0.0414515 (1946)	total: 26.2s	remaining: 6.54s
2400:	learn: 0.0908504	test: 0.0412699	best: 0.0412640 (2395)	total: 31.4s	remaining: 1.29s
2499:	learn: 0.0906146	test: 0.0412101	best: 0.0412097 (2498)	total: 32.7s	remaining: 0us
bestTest = 0.0412097168
bestIteration = 2498
Shrink model to first 2499 iterations.
0:	learn: 0.6379655	test: 0.6352006	best: 0.6352006 (0)	total: 20.1ms	remaining: 50.3s
400:	learn: 0.0990869	test: 0.0431333	best: 0.0431333 (400)	total: 5.28s	remaining: 27.6s
800:	learn: 0.0961617	test: 0.0425288	best: 0.0425284 (799)	total: 10.4s	remaining: 22s
1200:	learn: 0.0944172	test: 0.0421143	best: 0.0421118 (1197)	total: 15.5s	remaining: 16.7s
1600:	learn: 0.0930537	test: 0.0418028	best: 0.0418028 (1600)	total: 20.5s	remaining: 11.5s
2000:	learn: 0.0919046	test: 0.0416344	best: 0.0416344 (2000)	total: 25.7s	remaining: 6.41s
2400:	learn: 0.0909912	test: 0.0413853	best: 0.0413795 (2396)	total: 30.8s	remaining: 1.27s
2499:	learn: 0.0907760	test: 0.0413438	best: 0.0413438 (2499)	total: 32s	remaining: 0us
bestTest = 0.04134379387
bestIteration = 2499
0:	learn: 0.6360679	test: 0.6330714	best: 0.6330714 (0)	total: 26.4ms	remaining: 1m 6s
400:	learn: 0.0954705	test: 0.0422876	best: 0.0422876 (400)	total: 6.7s	remaining: 35.1s
800:	learn: 0.0915736	test: 0.0414972	best: 0.0414901 (797)	total: 13.3s	remaining: 28.2s
1200:	learn: 0.0890399	test: 0.0410007	best: 0.0410007 (1200)	total: 19.9s	remaining: 21.5s
1600:	learn: 0.0869857	test: 0.0407498	best: 0.0407498 (1600)	total: 26.4s	remaining: 14.8s
2000:	learn: 0.0852761	test: 0.0404392	best: 0.0404392 (2000)	total: 33s	remaining: 8.22s
2400:	learn: 0.0838213	test: 0.0402756	best: 0.0402750 (2398)	total: 39.5s	remaining: 1.63s
2499:	learn: 0.0834645	test: 0.0401942	best: 0.0401922 (2496)	total: 41.1s	remaining: 0us
bestTest = 0.0401922226
bestIteration = 2496
Shrink model to first 2497 iterations.
0:	learn: 0.5471314	test: 0.5392213	best: 0.5392213 (0)	total: 31.7ms	remaining: 1m 19s
400:	learn: 0.0864324	test: 0.0409338	best: 0.0408848 (393)	total: 7.69s	remaining: 40.2s
800:	learn: 0.0799171	test: 0.0398948	best: 0.0398917 (795)	total: 15.2s	remaining: 32.3s
1200:	learn: 0.0752572	test: 0.0393545	best: 0.0393352 (1176)	total: 22.8s	remaining: 24.6s
1600:	learn: 0.0717169	test: 0.0390303	best: 0.0390270 (1598)	total: 30.3s	remaining: 17s
2000:	learn: 0.0686975	test: 0.0386323	best: 0.0386321 (1997)	total: 37.9s	remaining: 9.46s
2400:	learn: 0.0659765	test: 0.0384638	best: 0.0384638 (2400)	total: 45.5s	remaining: 1.88s
2499:	learn: 0.0653288	test: 0.0383942	best: 0.0383942 (2499)	total: 47.4s	remaining: 0us
bestTest = 0.03839416186
bestIteration = 2499
0:	learn: 0.6002219	test: 0.5952828	best: 0.5952828 (0)	total: 26.4ms	remaining: 1m 5s
400:	learn: 0.0924919	test: 0.0417109	best: 0.0417109 (400)	total: 6.74s	remaining: 35.3s
800:	learn: 0.0877354	test: 0.0409472	best: 0.0409460 (798)	total: 13.2s	remaining: 28.1s
1200:	learn: 0.0844272	test: 0.0404930	best: 0.0404819 (1195)	total: 19.8s	remaining: 21.4s
1600:	learn: 0.0818576	test: 0.0401126	best: 0.0401124 (1598)	total: 26.4s	remaining: 14.8s
2000:	learn: 0.0797449	test: 0.0398878	best: 0.0398679 (1965)	total: 32.9s	remaining: 8.21s
bestTest = 0.0398679479
bestIteration = 1965
Shrink model to first 1966 iterations.
0:	learn: 0.5521462	test: 0.5449190	best: 0.5449190 (0)	total: 22.4ms	remaining: 56s
400:	learn: 0.0927008	test: 0.0416763	best: 0.0416727 (360)	total: 5.98s	remaining: 31.3s
800:	learn: 0.0886105	test: 0.0408786	best: 0.0408729 (794)	total: 11.7s	remaining: 24.8s
1200:	learn: 0.0856580	test: 0.0404920	best: 0.0404883 (1192)	total: 17.6s	remaining: 19s
bestTest = 0.04048827489
bestIteration = 1201
Shrink model to first 1202 iterations.

     ndcg@20                                             params  trees
11  0.096872  {'learning_rate': 0.03, 'l2_leaf_reg': 30, 'de...   2497
1   0.096341  {'learning_rate': 0.05, 'l2_leaf_reg': 30, 'de...   2486
14  0.096276  {'learning_rate': 0.08, 'l2_leaf_reg': 30, 'de...   1202
0   0.095880  {'learning_rate': 0.03, 'l2_leaf_reg': 10, 'de...   2490
13  0.095865  {'learning_rate': 0.05, 'l2_leaf_reg': 5, 'dep...   1966
4   0.095301  {'learning_rate': 0.08, 'l2_leaf_reg': 30, 'de...   2500
3   0.094906  {'learning_rate': 0.05, 'l2_leaf_reg': 30, 'de...   2497
2   0.094840  {'learning_rate': 0.08, 'l2_leaf_reg': 30, 'de...   1603
7   0.094475  {'learning_rate': 0.03, 'l2_leaf_reg': 10, 'de...   2497
12  0.093671  {'learning_rate': 0.08, 'l2_leaf_reg': 10, 'de...   2500
6   0.093508  {'learning_rate': 0.05, 'l2_leaf_reg': 10, 'de...   2447
8   0.093337  {'learning_rate': 0.08, 'l2_leaf_reg': 30, 'de...   1496
5   0.093106  {'learning_rate': 0.08, 'l2_leaf_reg': 10, 'de...   2498
10  0.092272  {'learning_rate': 0.03, 'l2_leaf_reg': 30, 'de...   2500
9   0.091745  {'learning_rate': 0.03, 'l2_leaf_reg': 10, 'de...   2499

In [31]:
a1_train = np.column_stack([np.load(LOCAL / 'learned_train.npy', mmap_mode='r')[cb_rows],
    train_store.a['common'][cb_rows]
])
a1_valid = np.column_stack([np.load(LOCAL / 'learned_valid.npy', mmap_mode='r')[valid_rows],
    valid_store.a['common'][valid_rows]
])

a1_search = tune('A1', a1_train, a1_valid, n_trials=15)
display(a1_search)

A1:   0%|          | 0/15 [00:00<?, ?it/s]

0:	learn: 0.6322959	test: 0.6295272	best: 0.6295272 (0)	total: 40.1ms	remaining: 1m 40s
400:	learn: 0.0931596	test: 0.0416992	best: 0.0416987 (399)	total: 9.15s	remaining: 47.9s
800:	learn: 0.0891018	test: 0.0413878	best: 0.0413878 (800)	total: 18.2s	remaining: 38.5s
1200:	learn: 0.0859907	test: 0.0411908	best: 0.0411901 (1198)	total: 27.2s	remaining: 29.4s
1600:	learn: 0.0833899	test: 0.0410090	best: 0.0410090 (1600)	total: 36.3s	remaining: 20.4s
2000:	learn: 0.0811116	test: 0.0408756	best: 0.0408748 (1993)	total: 45.4s	remaining: 11.3s
2400:	learn: 0.0789838	test: 0.0407610	best: 0.0407597 (2398)	total: 54.6s	remaining: 2.25s
2499:	learn: 0.0784750	test: 0.0407434	best: 0.0407434 (2499)	total: 56.9s	remaining: 0us
bestTest = 0.04074337324
bestIteration = 2499
0:	learn: 0.5961409	test: 0.5917901	best: 0.5917901 (0)	total: 34ms	remaining: 1m 25s
400:	learn: 0.0948568	test: 0.0420887	best: 0.0420876 (398)	total: 6.96s	remaining: 36.4s
800:	learn: 0.0919170	test: 0.0417637	best: 0.0417637 (800)	total: 13.5s	remaining: 28.6s
1200:	learn: 0.0897516	test: 0.0416435	best: 0.0416356 (1180)	total: 20.2s	remaining: 21.8s
1600:	learn: 0.0879857	test: 0.0415416	best: 0.0415393 (1591)	total: 26.7s	remaining: 15s
2000:	learn: 0.0864406	test: 0.0414467	best: 0.0414467 (2000)	total: 33.3s	remaining: 8.31s
2400:	learn: 0.0850096	test: 0.0413624	best: 0.0413624 (2400)	total: 40s	remaining: 1.65s
2499:	learn: 0.0846721	test: 0.0413460	best: 0.0413454 (2496)	total: 41.6s	remaining: 0us
bestTest = 0.04134542147
bestIteration = 2496
Shrink model to first 2497 iterations.
0:	learn: 0.5438037	test: 0.5369371	best: 0.5369371 (0)	total: 28.8ms	remaining: 1m 12s
400:	learn: 0.0930337	test: 0.0417808	best: 0.0417808 (400)	total: 6.74s	remaining: 35.3s
800:	learn: 0.0895302	test: 0.0415016	best: 0.0414993 (796)	total: 13.4s	remaining: 28.4s
1200:	learn: 0.0868723	test: 0.0413417	best: 0.0413363 (1158)	total: 20s	remaining: 21.6s
1600:	learn: 0.0845993	test: 0.0413011	best: 0.0412855 (1575)	total: 26.6s	remaining: 14.9s
2000:	learn: 0.0825762	test: 0.0411982	best: 0.0411928 (1995)	total: 33.3s	remaining: 8.31s
2400:	learn: 0.0807191	test: 0.0410445	best: 0.0410445 (2400)	total: 40s	remaining: 1.65s
2499:	learn: 0.0802976	test: 0.0410202	best: 0.0410183 (2451)	total: 41.7s	remaining: 0us
bestTest = 0.041018308
bestIteration = 2451
Shrink model to first 2452 iterations.
0:	learn: 0.5943824	test: 0.5898450	best: 0.5898450 (0)	total: 41.6ms	remaining: 1m 44s
400:	learn: 0.0909927	test: 0.0416277	best: 0.0416276 (399)	total: 9.39s	remaining: 49.1s
800:	learn: 0.0861931	test: 0.0412792	best: 0.0412783 (799)	total: 18.8s	remaining: 39.8s
1200:	learn: 0.0824289	test: 0.0410877	best: 0.0410861 (1199)	total: 28.1s	remaining: 30.4s
1600:	learn: 0.0792255	test: 0.0409072	best: 0.0409072 (1600)	total: 37.5s	remaining: 21.1s
2000:	learn: 0.0763846	test: 0.0406993	best: 0.0406986 (1996)	total: 46.9s	remaining: 11.7s
2400:	learn: 0.0737859	test: 0.0405739	best: 0.0405706 (2395)	total: 56.3s	remaining: 2.32s
2499:	learn: 0.0731466	test: 0.0405386	best: 0.0405350 (2497)	total: 58.7s	remaining: 0us
bestTest = 0.04053499222
bestIteration = 2497
Shrink model to first 2498 iterations.
0:	learn: 0.5431975	test: 0.5362564	best: 0.5362564 (0)	total: 33.1ms	remaining: 1m 22s
400:	learn: 0.0908584	test: 0.0416288	best: 0.0416217 (399)	total: 7.86s	remaining: 41.1s
800:	learn: 0.0863074	test: 0.0413525	best: 0.0413525 (800)	total: 15.7s	remaining: 33.3s
1200:	learn: 0.0826924	test: 0.0411133	best: 0.0411105 (1198)	total: 23.4s	remaining: 25.3s
1600:	learn: 0.0795477	test: 0.0410054	best: 0.0410007 (1596)	total: 31.2s	remaining: 17.5s
2000:	learn: 0.0767767	test: 0.0408604	best: 0.0408580 (1997)	total: 39.1s	remaining: 9.75s
2400:	learn: 0.0742888	test: 0.0407186	best: 0.0407145 (2384)	total: 47s	remaining: 1.94s
2499:	learn: 0.0736906	test: 0.0407071	best: 0.0406973 (2463)	total: 48.9s	remaining: 0us
bestTest = 0.04069729169
bestIteration = 2463
Shrink model to first 2464 iterations.
0:	learn: 0.5411187	test: 0.5339509	best: 0.5339509 (0)	total: 40.4ms	remaining: 1m 40s
400:	learn: 0.0873677	test: 0.0413546	best: 0.0413546 (400)	total: 9.43s	remaining: 49.4s
800:	learn: 0.0808446	test: 0.0409450	best: 0.0409388 (795)	total: 18.8s	remaining: 39.8s
1200:	learn: 0.0755714	test: 0.0407263	best: 0.0407235 (1177)	total: 28.1s	remaining: 30.4s
1600:	learn: 0.0711670	test: 0.0404864	best: 0.0404836 (1594)	total: 37.5s	remaining: 21.1s
2000:	learn: 0.0672646	test: 0.0402738	best: 0.0402738 (2000)	total: 47.1s	remaining: 11.7s
2400:	learn: 0.0636785	test: 0.0400879	best: 0.0400848 (2383)	total: 56.5s	remaining: 2.33s
2499:	learn: 0.0628795	test: 0.0400583	best: 0.0400583 (2499)	total: 58.8s	remaining: 0us
bestTest = 0.04005826632
bestIteration = 2499
0:	learn: 0.5987015	test: 0.5941226	best: 0.5941226 (0)	total: 29.5ms	remaining: 1m 13s
400:	learn: 0.0978728	test: 0.0425418	best: 0.0425364 (399)	total: 5.18s	remaining: 27.1s
800:	learn: 0.0957856	test: 0.0422703	best: 0.0422703 (800)	total: 10.4s	remaining: 22s
1200:	learn: 0.0944637	test: 0.0421317	best: 0.0421317 (1200)	total: 15.5s	remaining: 16.7s
1600:	learn: 0.0934497	test: 0.0420783	best: 0.0420715 (1590)	total: 20.6s	remaining: 11.6s
2000:	learn: 0.0925729	test: 0.0420003	best: 0.0420003 (2000)	total: 25.6s	remaining: 6.39s
2400:	learn: 0.0917860	test: 0.0419420	best: 0.0419420 (2400)	total: 30.8s	remaining: 1.27s
2499:	learn: 0.0916043	test: 0.0419237	best: 0.0419237 (2499)	total: 32s	remaining: 0us
bestTest = 0.04192370097
bestIteration = 2499
0:	learn: 0.6341390	test: 0.6315473	best: 0.6315473 (0)	total: 25.5ms	remaining: 1m 3s
400:	learn: 0.0978550	test: 0.0425084	best: 0.0425084 (400)	total: 5.98s	remaining: 31.3s
800:	learn: 0.0956899	test: 0.0422322	best: 0.0422322 (800)	total: 11.9s	remaining: 25.2s
1200:	learn: 0.0942773	test: 0.0420822	best: 0.0420822 (1200)	total: 17.6s	remaining: 19.1s
1600:	learn: 0.0931836	test: 0.0419848	best: 0.0419789 (1591)	total: 23.5s	remaining: 13.2s
2000:	learn: 0.0922229	test: 0.0418788	best: 0.0418787 (1973)	total: 29.3s	remaining: 7.3s
2400:	learn: 0.0913619	test: 0.0418006	best: 0.0417967 (2377)	total: 35.1s	remaining: 1.45s
2499:	learn: 0.0911768	test: 0.0417890	best: 0.0417882 (2490)	total: 36.5s	remaining: 0us
bestTest = 0.04178815524
bestIteration = 2490
Shrink model to first 2491 iterations.
0:	learn: 0.5476004	test: 0.5403692	best: 0.5403692 (0)	total: 20.9ms	remaining: 52.1s
400:	learn: 0.0965425	test: 0.0423878	best: 0.0423826 (399)	total: 5.16s	remaining: 27s
800:	learn: 0.0943855	test: 0.0421448	best: 0.0421446 (799)	total: 10.2s	remaining: 21.7s
1200:	learn: 0.0928303	test: 0.0419969	best: 0.0419907 (1198)	total: 15.3s	remaining: 16.5s
1600:	learn: 0.0916604	test: 0.0418938	best: 0.0418879 (1587)	total: 20.4s	remaining: 11.5s
2000:	learn: 0.0905944	test: 0.0418394	best: 0.0418293 (1876)	total: 25.5s	remaining: 6.37s
bestTest = 0.04182844798
bestIteration = 2024
Shrink model to first 2025 iterations.
0:	learn: 0.6350804	test: 0.6323080	best: 0.6323080 (0)	total: 20.6ms	remaining: 51.6s
400:	learn: 0.0992473	test: 0.0427501	best: 0.0427495 (397)	total: 5.22s	remaining: 27.3s
800:	learn: 0.0972812	test: 0.0424934	best: 0.0424934 (800)	total: 10.3s	remaining: 21.9s
1200:	learn: 0.0960842	test: 0.0423210	best: 0.0423194 (1199)	total: 15.5s	remaining: 16.7s
1600:	learn: 0.0951928	test: 0.0422120	best: 0.0422099 (1598)	total: 20.6s	remaining: 11.6s
2000:	learn: 0.0944507	test: 0.0421563	best: 0.0421558 (1991)	total: 25.7s	remaining: 6.42s
2400:	learn: 0.0937881	test: 0.0420891	best: 0.0420883 (2353)	total: 30.8s	remaining: 1.27s
2499:	learn: 0.0936314	test: 0.0420782	best: 0.0420768 (2495)	total: 32.1s	remaining: 0us
bestTest = 0.04207680384
bestIteration = 2495
Shrink model to first 2496 iterations.
0:	learn: 0.6350850	test: 0.6323107	best: 0.6323107 (0)	total: 20.6ms	remaining: 51.5s
400:	learn: 0.0992566	test: 0.0427547	best: 0.0427529 (397)	total: 5.3s	remaining: 27.7s
800:	learn: 0.0972665	test: 0.0425112	best: 0.0425112 (800)	total: 10.4s	remaining: 22.1s
1200:	learn: 0.0960927	test: 0.0423289	best: 0.0423280 (1196)	total: 15.6s	remaining: 16.9s
1600:	learn: 0.0952098	test: 0.0422126	best: 0.0422108 (1591)	total: 20.7s	remaining: 11.6s
2000:	learn: 0.0944726	test: 0.0421550	best: 0.0421550 (2000)	total: 25.8s	remaining: 6.44s
2400:	learn: 0.0938005	test: 0.0420847	best: 0.0420847 (2400)	total: 30.9s	remaining: 1.27s
2499:	learn: 0.0936570	test: 0.0420825	best: 0.0420785 (2474)	total: 32.1s	remaining: 0us
bestTest = 0.04207848231
bestIteration = 2474
Shrink model to first 2475 iterations.
0:	learn: 0.6334651	test: 0.6308312	best: 0.6308312 (0)	total: 28.6ms	remaining: 1m 11s
400:	learn: 0.0966598	test: 0.0422727	best: 0.0422679 (381)	total: 6.87s	remaining: 36s
800:	learn: 0.0941150	test: 0.0419586	best: 0.0419586 (800)	total: 13.5s	remaining: 28.6s
1200:	learn: 0.0923661	test: 0.0417919	best: 0.0417906 (1197)	total: 20.2s	remaining: 21.8s
1600:	learn: 0.0909662	test: 0.0416524	best: 0.0416524 (1600)	total: 26.9s	remaining: 15.1s
2000:	learn: 0.0897257	test: 0.0415670	best: 0.0415604 (1990)	total: 33.6s	remaining: 8.38s
2400:	learn: 0.0886248	test: 0.0414615	best: 0.0414608 (2397)	total: 40.3s	remaining: 1.66s
2499:	learn: 0.0883716	test: 0.0414562	best: 0.0414558 (2497)	total: 42s	remaining: 0us
bestTest = 0.04145583471
bestIteration = 2497
Shrink model to first 2498 iterations.
0:	learn: 0.5431699	test: 0.5362237	best: 0.5362237 (0)	total: 37.2ms	remaining: 1m 32s
400:	learn: 0.0905177	test: 0.0415771	best: 0.0415771 (400)	total: 7.78s	remaining: 40.7s
800:	learn: 0.0857128	test: 0.0412679	best: 0.0412679 (800)	total: 15.6s	remaining: 33.1s
1200:	learn: 0.0818621	test: 0.0410686	best: 0.0410668 (1199)	total: 23.4s	remaining: 25.3s
1600:	learn: 0.0785372	test: 0.0409006	best: 0.0409006 (1600)	total: 31.2s	remaining: 17.5s
2000:	learn: 0.0755967	test: 0.0407422	best: 0.0407420 (1992)	total: 39.1s	remaining: 9.74s
2400:	learn: 0.0728743	test: 0.0406368	best: 0.0406361 (2399)	total: 46.9s	remaining: 1.93s
2499:	learn: 0.0722557	test: 0.0406103	best: 0.0406103 (2499)	total: 48.7s	remaining: 0us
bestTest = 0.04061031977
bestIteration = 2499
0:	learn: 0.5961224	test: 0.5917663	best: 0.5917663 (0)	total: 28.8ms	remaining: 1m 12s
400:	learn: 0.0947283	test: 0.0420226	best: 0.0420054 (373)	total: 6.8s	remaining: 35.6s
800:	learn: 0.0916253	test: 0.0416901	best: 0.0416901 (800)	total: 13.4s	remaining: 28.4s
1200:	learn: 0.0893821	test: 0.0415334	best: 0.0415320 (1199)	total: 20.1s	remaining: 21.7s
1600:	learn: 0.0875084	test: 0.0414267	best: 0.0414260 (1593)	total: 26.7s	remaining: 15s
2000:	learn: 0.0858580	test: 0.0413366	best: 0.0413353 (1977)	total: 33.4s	remaining: 8.33s
2400:	learn: 0.0843255	test: 0.0412445	best: 0.0412445 (2400)	total: 40.1s	remaining: 1.65s
2499:	learn: 0.0839640	test: 0.0412336	best: 0.0412310 (2420)	total: 41.7s	remaining: 0us
bestTest = 0.04123096148
bestIteration = 2420
Shrink model to first 2421 iterations.
0:	learn: 0.5454075	test: 0.5386265	best: 0.5386265 (0)	total: 25.3ms	remaining: 1m 3s
400:	learn: 0.0948948	test: 0.0420731	best: 0.0420715 (394)	total: 5.89s	remaining: 30.8s
800:	learn: 0.0921841	test: 0.0417694	best: 0.0417694 (800)	total: 11.7s	remaining: 24.9s
1200:	learn: 0.0901857	test: 0.0416842	best: 0.0416657 (1127)	total: 17.6s	remaining: 19s
bestTest = 0.04165078799
bestIteration = 1325
Shrink model to first 1326 iterations.

     ndcg@20                                             params  trees
1   0.096034  {'learning_rate': 0.05, 'l2_leaf_reg': 30, 'de...   2497
11  0.095424  {'learning_rate': 0.03, 'l2_leaf_reg': 30, 'de...   2498
9   0.094986  {'learning_rate': 0.03, 'l2_leaf_reg': 10, 'de...   2496
10  0.094900  {'learning_rate': 0.03, 'l2_leaf_reg': 30, 'de...   2475
14  0.094353  {'learning_rate': 0.08, 'l2_leaf_reg': 30, 'de...   1326
6   0.094031  {'learning_rate': 0.05, 'l2_leaf_reg': 10, 'de...   2500
7   0.093850  {'learning_rate': 0.03, 'l2_leaf_reg': 10, 'de...   2491
13  0.093824  {'learning_rate': 0.05, 'l2_leaf_reg': 5, 'dep...   2421
8   0.093764  {'learning_rate': 0.08, 'l2_leaf_reg': 30, 'de...   2025
0   0.092440  {'learning_rate': 0.03, 'l2_leaf_reg': 10, 'de...   2500
3   0.091840  {'learning_rate': 0.05, 'l2_leaf_reg': 30, 'de...   2498
2   0.091557  {'learning_rate': 0.08, 'l2_leaf_reg': 30, 'de...   2452
12  0.090646  {'learning_rate': 0.08, 'l2_leaf_reg': 10, 'de...   2500
4   0.090435  {'learning_rate': 0.08, 'l2_leaf_reg': 30, 'de...   2464
5   0.088916  {'learning_rate': 0.08, 'l2_leaf_reg': 10, 'de...   2500

## Валидация

In [33]:
def ranking_report(scores,store,total,name):
    score=np.asarray(scores,dtype=np.float32).reshape(N_USERS,C)
    labels=np.asarray(store.a['y']).reshape(N_USERS,C)
    ranked=np.argsort(-score,axis=1,kind='stable')[:,:100]
    found=np.take_along_axis(labels,ranked,axis=1)
    discount=1/np.log2(np.arange(2,102))
    dcg=np.cumsum(found*discount,axis=1)
    ideal=np.r_[0,np.cumsum(discount)]
    candidate_found=labels.sum(axis=1)
    out=dict(model=name,
        roc_auc=roc_auc_score(labels.ravel(),score.ravel()),
        logloss=log_loss(labels.ravel(),np.clip(score.ravel(),1e-7,1-1e-7)) if name!='R0' else np.nan)
    for k in (5,10,20,100):
        value=dcg[:,k-1]
        out[f'ndcg@{k}']=np.where(total>0,value/np.maximum(ideal[np.minimum(total,k)],1),0).mean()
        out[f'ndcg@{k}_conditional']=np.where(candidate_found>0,
              value/np.maximum(ideal[np.minimum(candidate_found,k)],1),0)[candidate_found>0].mean()
        out[f'recall@{k}']=np.where(total>0,found[:,:k].sum(axis=1)/np.maximum(total,1),0).mean()
    return out

def predict_manual_full(split,model):
    filename=R2/'features'/f'features_{split}.parquet'
    values=[]
    for b in tqdm(pq.ParquetFile(filename).iter_batches(batch_size=100_000,columns=manual_cols),
                  desc=f'Manual {split}'):
        frame=b.to_pandas()
        values.append(model.predict_proba(frame[manual_cols])[:,1].astype(np.float32))
    return np.concatenate(values)

def predict_adaptive_full(split,model):
    st=RelationStore(split)
    feat=np.load(LOCAL/f'learned_{split}.npy',mmap_mode='r')
    result=np.empty(st.n,np.float32)
    for left in tqdm(range(0,st.n,100_000),desc=f'AutoFE {split}'):
        right=min(st.n,left+100_000)
        x=np.column_stack([feat[left:right].astype(np.float32),
                           np.asarray(st.a['common'][left:right],dtype=np.float32)])
        result[left:right]=model.predict_proba(x)[:,1].astype(np.float32)
    return result

r2_best = CatBoostClassifier()
r2_best.load_model(str(OUT / 'R2_best.cbm'))

a1_best = CatBoostClassifier()
a1_best.load_model(str(OUT / 'A1_best.cbm'))

truth_valid = future_totals('valid')

s2 = predict_manual_full('valid', r2_best)
s1 = predict_adaptive_full('valid', a1_best)
scores = {'R2': s2, 'AutoFE': s1}

results = pd.DataFrame([
    ranking_report(s2, valid_store, truth_valid, 'R2_tuned'),
    ranking_report(s1, valid_store, truth_valid, 'A1_tuned')
])

display(results)
results.to_csv(OUT/'validation_metrics.csv',index=False)
np.save(OUT/'scores_R2_valid.npy',s2)
np.save(OUT/'scores_A1_valid.npy',s1)

Manual valid: 0it [00:00, ?it/s]

AutoFE valid:   0%|          | 0/60 [00:00<?, ?it/s]

,model,roc_auc,logloss,ndcg@5,ndcg@5_conditional,recall@5,ndcg@10,ndcg@10_conditional,recall@10,ndcg@20,ndcg@20_conditional,recall@20,ndcg@100,ndcg@100_conditional,recall@100
0,R2_tuned,0.914900,0.040061,0.103298,0.286012,0.031639,0.094611,0.296224,0.046771,0.088879,0.323234,0.064349,0.095825,0.423476,0.112844
1,A1_tuned,0.915957,0.041338,0.102687,0.284657,0.032182,0.093553,0.294472,0.047111,0.087792,0.321668,0.064181,0.095656,0.424497,0.114092

## История кандидатов

In [41]:
SEQ_L, SEQ_EPOCHS = 50, 10
names = hist_days.name.tolist() + ['train', 'valid', 'test']
ends = np.r_[hist_days.history_end, [snaps.loc[s].history_end for s in ('train', 'valid', 'test')]].astype(np.int64)
order = np.argsort(ends)

@njit
def last_tracks(u, item, ts, event, cutoffs, n_users, L):
    buf = np.zeros((n_users, L), np.int32)
    tbuf = np.zeros((n_users, L), np.int64)
    count = np.zeros(n_users, np.int32)
    ids = np.zeros((len(cutoffs), n_users, L), np.int32)
    ages = np.zeros_like(ids, dtype=np.float32)
    p = 0
    for k, cutoff in enumerate(cutoffs):
        while p < len(ts) and ts[p] < cutoff:
            if event[p] == 1:
                a = u[p]; j = count[a] % L
                buf[a, j], tbuf[a, j] = item[p] + 1, ts[p]
                count[a] += 1
            p += 1
        for a in range(n_users):
            for j in range(min(count[a], L)):
                q = (count[a] - j - 1) % L
                ids[k, a, j] = buf[a, q]
                ages[k, a, j] = (cutoff - tbuf[a, q]) / DAY
    return ids, ages

ids, ages = last_tracks(EU, EI, ET, EK, ends[order], N_USERS, SEQ_L)
hist_id = {names[i]: ids[j] for j, i in enumerate(order)}
hist_age = {names[i]: ages[j] for j, i in enumerate(order)}
del ids, ages


class CandidateSeq(nn.Module):
    def __init__(self):
        super().__init__()
        self.emb = nn.Embedding(N_ITEMS + 1, 32, padding_idx=0, sparse=True)
        self.time = nn.Linear(1, 1)
        self.proj = nn.Linear(96, 5)
        self.head = nn.Linear(5, 1)

    def forward(self, item, history, age):
        q, h = self.emb(item + 1), self.emb(history)
        mask = (history > 0) & (history != item[:, None] + 1)
        logits = (q[:, None] * h).sum(-1) / 32**0.5
        logits += self.time(torch.log1p(age)[..., None]).squeeze(-1)
        w = logits.masked_fill(~mask, -1e4).softmax(1) * mask
        w = w / w.sum(1, keepdim=True).clamp_min(1e-8)
        z = (w[..., None] * h).sum(1)
        features = torch.tanh(self.proj(torch.cat([q, z, q*z], dim=1)))
        return self.head(features).squeeze(-1), features

def seq_forward(net, st, name, rows):
    u = st.a['cand_u'][rows]
    return net(torch.as_tensor(st.a['cand_i'][rows], device=DEVICE, dtype=torch.long),
               torch.as_tensor(hist_id[name][u], device=DEVICE, dtype=torch.long),
               torch.as_tensor(hist_age[name][u], device=DEVICE))

## Обучение Seq

In [42]:
seq = CandidateSeq().to(DEVICE)
opt_emb = torch.optim.SparseAdam(seq.emb.parameters(), lr=.001)
opt_head = torch.optim.AdamW(
    list(seq.time.parameters()) + list(seq.proj.parameters()) +
    list(seq.head.parameters()), lr=.003
)
dev_name = hist_days.name.iloc[-1]
dev = RelationStore(dev_name)
best, bad = -1., 0

@torch.no_grad()
def seq_predict(name, st, rows, features=False):
    seq.eval()
    result = []
    for p in range(0, len(rows), 4096):
        score, feat = seq_forward(seq, st, name, rows[p:p+4096])
        result.append((torch.cat([feat, score[:, None]], 1) if features else score).cpu().numpy())
    return np.concatenate(result)

for epoch in range(SEQ_EPOCHS):
    seq.train(); losses = []
    for name in rng.permutation(hist_days.name.iloc[-6:-1]):
        st = RelationStore(name)
        groups = rng.permutation(st.n // (NEG + 1))
        for p in tqdm(range(0, len(groups), 256), desc=f'Seq {epoch+1}: {name}', leave=False):
            g = groups[p:p+256]
            rows = (g[:, None]*(NEG+1) + np.arange(NEG+1)).ravel()
            score, _ = seq_forward(seq, st, name, rows)
            loss = F.cross_entropy(score.reshape(len(g), NEG+1),
                                   torch.zeros(len(g), device=DEVICE, dtype=torch.long))
            opt_emb.zero_grad(); opt_head.zero_grad()
            loss.backward(); opt_emb.step(); opt_head.step()
            losses.append(loss.item())
    g = min(4000, dev.n // (NEG+1))
    rows = (np.arange(g)[:, None]*(NEG+1) + np.arange(NEG+1)).ravel()
    score = seq_predict(dev_name, dev, rows).reshape(g, NEG+1)
    rank = (score[:, 1:] >= score[:, :1]).sum(1)
    ndcg = np.where(rank < 10, 1/np.log2(rank+2), 0).mean()
    print(f'Seq epoch {epoch+1}: loss={np.mean(losses):.4f}, dev NDCG@10={ndcg:.5f}')
    if ndcg > best + 1e-4:
        best, bad = ndcg, 0
        torch.save(seq.state_dict(), OUT/'seq_encoder.pt')
    else:
        bad += 1
        if bad == 2: break

seq.load_state_dict(torch.load(OUT/'seq_encoder.pt', map_location=DEVICE, weights_only=True))
for name in ('train', 'valid'):
    st = RelationStore(name)
    dest = LOCAL/f'seq_{name}.npy'
    tmp = LOCAL/f'seq_{name}.partial.npy'
    out = np.lib.format.open_memmap(tmp, mode='w+', dtype=np.float16, shape=(st.n, 6))
    for p in tqdm(range(0, st.n, 4096), desc=f'Seq features {name}'):
        rows = np.arange(p, min(p+4096, st.n))
        out[rows] = seq_predict(name, st, rows, features=True).astype(np.float16)
    out.flush(); del out
    finish_feature(tmp, dest, (st.n, 6), OUT/'seq_encoder.pt', name)
    shutil.copy2(dest, OUT/f'seq_{name}.npy')

Seq 1: hist_5:   0%|          | 0/115 [00:00<?, ?it/s]

Seq 1: hist_6:   0%|          | 0/114 [00:00<?, ?it/s]

Seq 1: hist_8:   0%|          | 0/108 [00:00<?, ?it/s]

Seq 1: hist_7:   0%|          | 0/112 [00:00<?, ?it/s]

Seq 1: hist_4:   0%|          | 0/122 [00:00<?, ?it/s]

Seq epoch 1: loss=2.5649, dev NDCG@10=0.35484

Seq 2: hist_8:   0%|          | 0/108 [00:00<?, ?it/s]

Seq 2: hist_7:   0%|          | 0/112 [00:00<?, ?it/s]

Seq 2: hist_5:   0%|          | 0/115 [00:00<?, ?it/s]

Seq 2: hist_4:   0%|          | 0/122 [00:00<?, ?it/s]

Seq 2: hist_6:   0%|          | 0/114 [00:00<?, ?it/s]

Seq epoch 2: loss=2.5557, dev NDCG@10=0.36251

Seq 3: hist_8:   0%|          | 0/108 [00:00<?, ?it/s]

Seq 3: hist_7:   0%|          | 0/112 [00:00<?, ?it/s]

Seq 3: hist_5:   0%|          | 0/115 [00:00<?, ?it/s]

Seq 3: hist_4:   0%|          | 0/122 [00:00<?, ?it/s]

Seq 3: hist_6:   0%|          | 0/114 [00:00<?, ?it/s]

Seq epoch 3: loss=2.5144, dev NDCG@10=0.36606

Seq 4: hist_5:   0%|          | 0/115 [00:00<?, ?it/s]

Seq 4: hist_7:   0%|          | 0/112 [00:00<?, ?it/s]

Seq 4: hist_6:   0%|          | 0/114 [00:00<?, ?it/s]

Seq 4: hist_4:   0%|          | 0/122 [00:00<?, ?it/s]

Seq 4: hist_8:   0%|          | 0/108 [00:00<?, ?it/s]

Seq epoch 4: loss=2.4406, dev NDCG@10=0.36769

Seq 5: hist_5:   0%|          | 0/115 [00:00<?, ?it/s]

Seq 5: hist_6:   0%|          | 0/114 [00:00<?, ?it/s]

Seq 5: hist_4:   0%|          | 0/122 [00:00<?, ?it/s]

Seq 5: hist_8:   0%|          | 0/108 [00:00<?, ?it/s]

Seq 5: hist_7:   0%|          | 0/112 [00:00<?, ?it/s]

Seq epoch 5: loss=2.3390, dev NDCG@10=0.36414

Seq 6: hist_6:   0%|          | 0/114 [00:00<?, ?it/s]

Seq 6: hist_8:   0%|          | 0/108 [00:00<?, ?it/s]

Seq 6: hist_4:   0%|          | 0/122 [00:00<?, ?it/s]

Seq 6: hist_7:   0%|          | 0/112 [00:00<?, ?it/s]

Seq 6: hist_5:   0%|          | 0/115 [00:00<?, ?it/s]

Seq epoch 6: loss=2.2260, dev NDCG@10=0.36554

Seq features train:   0%|          | 0/1465 [00:00<?, ?it/s]

Seq features valid:   0%|          | 0/1465 [00:00<?, ?it/s]

## Ручной контроль

In [50]:
def manual_seq(split, rows):
    st = globals()[f'{split}_store']
    u, i = st.a['cand_u'][rows], st.a['cand_i'][rows]
    h, age = hist_id[split][u], hist_age[split][u]
    m = h == i[:, None] + 1
    last = np.where(m, age, np.inf).min(axis=1)

    return np.column_stack([
        m.sum(1), m[:, :5].sum(1),
        (m & (age <= 7)).sum(1),
        (m & (age <= 30)).sum(1),
        (m * np.exp(-age / 7)).sum(1),
        (m * np.exp(-age / 60)).sum(1),
        np.log1p(np.where(np.isfinite(last), last, 1000)),
        m[:, 0]
    ]).astype(np.float32)

Xtr = np.column_stack([
    load_manual('train', cb_rows)[manual_cols],
    manual_seq('train', cb_rows)
])
Xva = np.column_stack([
    load_manual('valid', valid_rows)[manual_cols],
    manual_seq('valid', valid_rows)
])

manual_seq_search = tune('R2_ManualSeq', Xtr, Xva)
display(manual_seq_search.head())

model = CatBoostClassifier()
model.load_model(str(OUT / 'R2_ManualSeq_best.cbm'))

pred = np.empty(valid_store.n, np.float32)
offset = 0
for batch in tqdm(pq.ParquetFile(R2/'features'/'features_valid.parquet')
                  .iter_batches(batch_size=100_000, columns=manual_cols)):
    n = batch.num_rows
    r = slice(offset, offset + n)
    X = np.column_stack([
        batch.to_pandas()[manual_cols].to_numpy(np.float32),
        manual_seq('valid', r)
    ])
    pred[r] = model.predict_proba(X)[:, 1]
    offset += n

R2_ManualSeq:   0%|          | 0/10 [00:00<?, ?it/s]

0:	learn: 0.6345120	test: 0.6318426	best: 0.6318426 (0)	total: 36.9ms	remaining: 1m 32s
400:	learn: 0.0911412	test: 0.0413551	best: 0.0413551 (400)	total: 8.72s	remaining: 45.6s
800:	learn: 0.0854350	test: 0.0404987	best: 0.0404987 (800)	total: 17.4s	remaining: 36.9s
1200:	learn: 0.0813347	test: 0.0398648	best: 0.0398579 (1197)	total: 26.1s	remaining: 28.2s
1600:	learn: 0.0782033	test: 0.0395169	best: 0.0395169 (1600)	total: 34.8s	remaining: 19.6s
2000:	learn: 0.0755159	test: 0.0392000	best: 0.0392000 (2000)	total: 43.7s	remaining: 10.9s
2400:	learn: 0.0731195	test: 0.0388862	best: 0.0388862 (2400)	total: 52.5s	remaining: 2.17s
2499:	learn: 0.0725999	test: 0.0388361	best: 0.0388332 (2467)	total: 54.7s	remaining: 0us
bestTest = 0.0388332208
bestIteration = 2467
Shrink model to first 2468 iterations.
0:	learn: 0.6017328	test: 0.5968432	best: 0.5968432 (0)	total: 25.1ms	remaining: 1m 2s
400:	learn: 0.0927666	test: 0.0416373	best: 0.0416373 (400)	total: 6.56s	remaining: 34.3s
800:	learn: 0.0884655	test: 0.0409186	best: 0.0409094 (799)	total: 13.1s	remaining: 27.7s
1200:	learn: 0.0853944	test: 0.0404281	best: 0.0404281 (1200)	total: 19.5s	remaining: 21.1s
1600:	learn: 0.0831223	test: 0.0401381	best: 0.0401381 (1600)	total: 26s	remaining: 14.6s
2000:	learn: 0.0811526	test: 0.0398659	best: 0.0398583 (1984)	total: 32.6s	remaining: 8.12s
2400:	learn: 0.0794863	test: 0.0396780	best: 0.0396768 (2395)	total: 39s	remaining: 1.61s
2499:	learn: 0.0791134	test: 0.0396244	best: 0.0396218 (2495)	total: 40.7s	remaining: 0us
bestTest = 0.03962179184
bestIteration = 2495
Shrink model to first 2496 iterations.
0:	learn: 0.5519777	test: 0.5442861	best: 0.5442861 (0)	total: 24.9ms	remaining: 1m 2s
400:	learn: 0.0900593	test: 0.0413111	best: 0.0413109 (399)	total: 6.67s	remaining: 34.9s
800:	learn: 0.0851285	test: 0.0405031	best: 0.0404788 (780)	total: 13.2s	remaining: 28s
1200:	learn: 0.0815947	test: 0.0399256	best: 0.0399195 (1185)	total: 19.8s	remaining: 21.4s
bestTest = 0.03976020495
bestIteration = 1443
Shrink model to first 1444 iterations.
0:	learn: 0.5977929	test: 0.5933892	best: 0.5933892 (0)	total: 39.2ms	remaining: 1m 37s
400:	learn: 0.0877766	test: 0.0411542	best: 0.0411470 (393)	total: 9.07s	remaining: 47.5s
800:	learn: 0.0815072	test: 0.0401835	best: 0.0401796 (799)	total: 18s	remaining: 38.1s
1200:	learn: 0.0769812	test: 0.0393826	best: 0.0393774 (1193)	total: 27s	remaining: 29.2s
1600:	learn: 0.0736992	test: 0.0390498	best: 0.0390498 (1600)	total: 36s	remaining: 20.2s
2000:	learn: 0.0707850	test: 0.0386730	best: 0.0386728 (1998)	total: 45.1s	remaining: 11.3s
2400:	learn: 0.0681686	test: 0.0384470	best: 0.0384296 (2326)	total: 54.3s	remaining: 2.24s
2499:	learn: 0.0675747	test: 0.0384067	best: 0.0383989 (2496)	total: 56.5s	remaining: 0us
bestTest = 0.03839885394
bestIteration = 2496
Shrink model to first 2497 iterations.
0:	learn: 0.5503121	test: 0.5424795	best: 0.5424795 (0)	total: 30.8ms	remaining: 1m 17s
400:	learn: 0.0873595	test: 0.0409050	best: 0.0409050 (400)	total: 7.71s	remaining: 40.3s
800:	learn: 0.0814242	test: 0.0399676	best: 0.0399676 (800)	total: 15.3s	remaining: 32.5s
1200:	learn: 0.0770972	test: 0.0395557	best: 0.0395405 (1198)	total: 22.9s	remaining: 24.7s
1600:	learn: 0.0737738	test: 0.0392738	best: 0.0392738 (1600)	total: 30.5s	remaining: 17.1s
2000:	learn: 0.0709347	test: 0.0389693	best: 0.0389693 (2000)	total: 38.2s	remaining: 9.53s
2400:	learn: 0.0683657	test: 0.0386665	best: 0.0386626 (2396)	total: 45.9s	remaining: 1.89s
2499:	learn: 0.0678139	test: 0.0386399	best: 0.0386252 (2496)	total: 47.7s	remaining: 0us
bestTest = 0.03862521172
bestIteration = 2496
Shrink model to first 2497 iterations.
0:	learn: 0.5461761	test: 0.5392267	best: 0.5392267 (0)	total: 39.8ms	remaining: 1m 39s
400:	learn: 0.0825961	test: 0.0406789	best: 0.0406269 (370)	total: 9.07s	remaining: 47.5s
800:	learn: 0.0747594	test: 0.0395647	best: 0.0395632 (798)	total: 18.1s	remaining: 38.4s
1200:	learn: 0.0690713	test: 0.0390168	best: 0.0390105 (1193)	total: 27.3s	remaining: 29.5s
1600:	learn: 0.0646375	test: 0.0385534	best: 0.0385534 (1600)	total: 36.4s	remaining: 20.4s
2000:	learn: 0.0607557	test: 0.0381972	best: 0.0381915 (1984)	total: 45.6s	remaining: 11.4s
2400:	learn: 0.0574033	test: 0.0379145	best: 0.0379077 (2360)	total: 54.7s	remaining: 2.26s
2499:	learn: 0.0565970	test: 0.0377911	best: 0.0377911 (2499)	total: 57s	remaining: 0us
bestTest = 0.0377910614
bestIteration = 2499
0:	learn: 0.6032289	test: 0.5986585	best: 0.5986585 (0)	total: 20.6ms	remaining: 51.5s
400:	learn: 0.0970494	test: 0.0425332	best: 0.0425332 (400)	total: 5.25s	remaining: 27.5s
800:	learn: 0.0940453	test: 0.0418579	best: 0.0418579 (799)	total: 10.4s	remaining: 22s
1200:	learn: 0.0920422	test: 0.0415065	best: 0.0415027 (1192)	total: 15.5s	remaining: 16.7s
1600:	learn: 0.0905023	test: 0.0412524	best: 0.0412441 (1592)	total: 20.6s	remaining: 11.6s
2000:	learn: 0.0891536	test: 0.0409719	best: 0.0409719 (2000)	total: 25.7s	remaining: 6.42s
2400:	learn: 0.0880269	test: 0.0407893	best: 0.0407793 (2396)	total: 30.9s	remaining: 1.27s
2499:	learn: 0.0877604	test: 0.0407664	best: 0.0407604 (2497)	total: 32.2s	remaining: 0us
bestTest = 0.04076038361
bestIteration = 2497
Shrink model to first 2498 iterations.
0:	learn: 0.6379616	test: 0.6351966	best: 0.6351966 (0)	total: 22.4ms	remaining: 56.1s
400:	learn: 0.0972755	test: 0.0425956	best: 0.0425956 (400)	total: 6.01s	remaining: 31.4s
800:	learn: 0.0939489	test: 0.0419300	best: 0.0419271 (798)	total: 11.8s	remaining: 25.1s
1200:	learn: 0.0917941	test: 0.0415061	best: 0.0415061 (1192)	total: 17.6s	remaining: 19.1s
1600:	learn: 0.0901002	test: 0.0411146	best: 0.0411137 (1585)	total: 23.5s	remaining: 13.2s
2000:	learn: 0.0886328	test: 0.0409293	best: 0.0409167 (1976)	total: 29.3s	remaining: 7.32s
2400:	learn: 0.0873732	test: 0.0406739	best: 0.0406702 (2398)	total: 35.1s	remaining: 1.45s
2499:	learn: 0.0871063	test: 0.0406502	best: 0.0406469 (2493)	total: 36.6s	remaining: 0us
bestTest = 0.04064688365
bestIteration = 2493
Shrink model to first 2494 iterations.
0:	learn: 0.5541909	test: 0.5469706	best: 0.5469706 (0)	total: 31.5ms	remaining: 1m 18s
400:	learn: 0.0950427	test: 0.0421342	best: 0.0421046 (396)	total: 5.19s	remaining: 27.2s
800:	learn: 0.0918208	test: 0.0416006	best: 0.0415961 (799)	total: 10.3s	remaining: 21.9s
1200:	learn: 0.0896817	test: 0.0412276	best: 0.0411136 (1153)	total: 15.4s	remaining: 16.7s
bestTest = 0.0411135896
bestIteration = 1153
Shrink model to first 1154 iterations.
0:	learn: 0.6379629	test: 0.6351970	best: 0.6351970 (0)	total: 20.5ms	remaining: 51.2s
400:	learn: 0.0989791	test: 0.0431030	best: 0.0431030 (400)	total: 5.26s	remaining: 27.5s
800:	learn: 0.0961938	test: 0.0424708	best: 0.0424708 (800)	total: 10.4s	remaining: 22s
1200:	learn: 0.0944161	test: 0.0421266	best: 0.0421118 (1196)	total: 15.5s	remaining: 16.7s
1600:	learn: 0.0931390	test: 0.0418366	best: 0.0418360 (1599)	total: 20.6s	remaining: 11.6s
2000:	learn: 0.0919737	test: 0.0415394	best: 0.0415347 (1979)	total: 25.8s	remaining: 6.43s
2400:	learn: 0.0910080	test: 0.0413490	best: 0.0413463 (2398)	total: 30.9s	remaining: 1.28s
2499:	learn: 0.0907914	test: 0.0412910	best: 0.0412910 (2499)	total: 32.2s	remaining: 0us
bestTest = 0.04129103661
bestIteration = 2499

    ndcg@20                                             params  trees
1  0.097298  {'learning_rate': 0.05, 'l2_leaf_reg': 30, 'de...   2496
0  0.095088  {'learning_rate': 0.03, 'l2_leaf_reg': 10, 'de...   2468
3  0.094729  {'learning_rate': 0.05, 'l2_leaf_reg': 30, 'de...   2497
2  0.093799  {'learning_rate': 0.08, 'l2_leaf_reg': 30, 'de...   1444
6  0.093365  {'learning_rate': 0.05, 'l2_leaf_reg': 10, 'de...   2498

0it [00:00, ?it/s]

In [51]:
scores['R2+ManualSeq'] = pred

## Сравнение

In [55]:
A = {s: np.load(LOCAL/f'learned_{s}.npy', mmap_mode='r') for s in ('train', 'valid')}
S = {s: np.load(LOCAL/f'seq_{s}.npy', mmap_mode='r') for s in ('train', 'valid')}

def seq_features(split, rows):
    st = globals()[f'{split}_store']
    return np.column_stack([A[split][rows], st.a['common'][rows], S[split][rows]])

seq_search = tune(
    'AutoFE_Seq',
    seq_features('train', cb_rows),
    seq_features('valid', valid_rows)
)
display(seq_search.head())

AutoFE_Seq:   0%|          | 0/10 [00:00<?, ?it/s]

0:	learn: 0.6322959	test: 0.6295272	best: 0.6295272 (0)	total: 40.5ms	remaining: 1m 41s
400:	learn: 0.0931118	test: 0.0417319	best: 0.0417313 (399)	total: 9.28s	remaining: 48.6s
800:	learn: 0.0891305	test: 0.0413865	best: 0.0413865 (800)	total: 18.5s	remaining: 39.3s
1200:	learn: 0.0861264	test: 0.0411648	best: 0.0411585 (1193)	total: 27.7s	remaining: 30s
1600:	learn: 0.0835215	test: 0.0410016	best: 0.0410016 (1600)	total: 37s	remaining: 20.8s
2000:	learn: 0.0812477	test: 0.0408655	best: 0.0408652 (1997)	total: 46.3s	remaining: 11.5s
2400:	learn: 0.0790685	test: 0.0407045	best: 0.0407044 (2399)	total: 55.6s	remaining: 2.29s
2499:	learn: 0.0785641	test: 0.0406723	best: 0.0406723 (2499)	total: 57.9s	remaining: 0us
bestTest = 0.04067227046
bestIteration = 2499
0:	learn: 0.5961409	test: 0.5917902	best: 0.5917902 (0)	total: 28.7ms	remaining: 1m 11s
400:	learn: 0.0948406	test: 0.0420788	best: 0.0420741 (383)	total: 7.2s	remaining: 37.7s
800:	learn: 0.0919809	test: 0.0417726	best: 0.0417715 (799)	total: 13.9s	remaining: 29.4s
1200:	learn: 0.0898182	test: 0.0416293	best: 0.0416261 (1198)	total: 20.6s	remaining: 22.3s
1600:	learn: 0.0880255	test: 0.0414783	best: 0.0414783 (1600)	total: 27.2s	remaining: 15.3s
2000:	learn: 0.0864525	test: 0.0413819	best: 0.0413800 (1996)	total: 33.9s	remaining: 8.46s
2400:	learn: 0.0850358	test: 0.0412610	best: 0.0412605 (2395)	total: 40.7s	remaining: 1.68s
2499:	learn: 0.0846883	test: 0.0412504	best: 0.0412484 (2428)	total: 42.4s	remaining: 0us
bestTest = 0.04124843597
bestIteration = 2428
Shrink model to first 2429 iterations.
0:	learn: 0.5438037	test: 0.5369371	best: 0.5369371 (0)	total: 28.9ms	remaining: 1m 12s
400:	learn: 0.0930682	test: 0.0418750	best: 0.0418633 (394)	total: 6.8s	remaining: 35.6s
800:	learn: 0.0896240	test: 0.0415709	best: 0.0415696 (799)	total: 13.5s	remaining: 28.7s
1200:	learn: 0.0869520	test: 0.0414613	best: 0.0414595 (1199)	total: 20.3s	remaining: 22s
1600:	learn: 0.0847060	test: 0.0413882	best: 0.0413717 (1504)	total: 27.1s	remaining: 15.2s
2000:	learn: 0.0826941	test: 0.0413142	best: 0.0412932 (1957)	total: 33.8s	remaining: 8.43s
2400:	learn: 0.0807794	test: 0.0412039	best: 0.0412007 (2349)	total: 40.6s	remaining: 1.67s
2499:	learn: 0.0803492	test: 0.0412014	best: 0.0411970 (2404)	total: 42.3s	remaining: 0us
bestTest = 0.04119696935
bestIteration = 2404
Shrink model to first 2405 iterations.
0:	learn: 0.5943825	test: 0.5898451	best: 0.5898451 (0)	total: 43.4ms	remaining: 1m 48s
400:	learn: 0.0910484	test: 0.0416831	best: 0.0416765 (397)	total: 9.66s	remaining: 50.6s
800:	learn: 0.0862326	test: 0.0413518	best: 0.0413518 (800)	total: 19.1s	remaining: 40.5s
1200:	learn: 0.0824884	test: 0.0411149	best: 0.0411114 (1197)	total: 28.6s	remaining: 31s
1600:	learn: 0.0792864	test: 0.0409424	best: 0.0409424 (1600)	total: 38.3s	remaining: 21.5s
2000:	learn: 0.0763264	test: 0.0407491	best: 0.0407491 (2000)	total: 47.9s	remaining: 12s
2400:	learn: 0.0736330	test: 0.0405669	best: 0.0405669 (2400)	total: 57.5s	remaining: 2.37s
2499:	learn: 0.0729704	test: 0.0405271	best: 0.0405271 (2499)	total: 60s	remaining: 0us
bestTest = 0.04052714666
bestIteration = 2499
0:	learn: 0.5431974	test: 0.5362564	best: 0.5362564 (0)	total: 34ms	remaining: 1m 24s
400:	learn: 0.0909500	test: 0.0415969	best: 0.0415919 (399)	total: 7.94s	remaining: 41.6s
800:	learn: 0.0863024	test: 0.0413212	best: 0.0413212 (800)	total: 15.8s	remaining: 33.5s
1200:	learn: 0.0826751	test: 0.0411387	best: 0.0411387 (1200)	total: 23.7s	remaining: 25.7s
1600:	learn: 0.0795353	test: 0.0409926	best: 0.0409897 (1596)	total: 31.8s	remaining: 17.8s
2000:	learn: 0.0767426	test: 0.0409089	best: 0.0408998 (1919)	total: 39.8s	remaining: 9.92s
2400:	learn: 0.0742156	test: 0.0408155	best: 0.0408155 (2400)	total: 47.7s	remaining: 1.97s
2499:	learn: 0.0736314	test: 0.0407962	best: 0.0407888 (2482)	total: 49.7s	remaining: 0us
bestTest = 0.04078876813
bestIteration = 2482
Shrink model to first 2483 iterations.
0:	learn: 0.5411187	test: 0.5339510	best: 0.5339510 (0)	total: 40.3ms	remaining: 1m 40s
400:	learn: 0.0874765	test: 0.0413404	best: 0.0413255 (364)	total: 9.57s	remaining: 50.1s
800:	learn: 0.0810150	test: 0.0409685	best: 0.0409603 (795)	total: 19s	remaining: 40.4s
1200:	learn: 0.0758696	test: 0.0407729	best: 0.0407729 (1200)	total: 28.6s	remaining: 30.9s
1600:	learn: 0.0713710	test: 0.0404884	best: 0.0404833 (1598)	total: 38.2s	remaining: 21.4s
2000:	learn: 0.0673561	test: 0.0402833	best: 0.0402833 (2000)	total: 47.7s	remaining: 11.9s
2400:	learn: 0.0636688	test: 0.0401028	best: 0.0401028 (2400)	total: 57.4s	remaining: 2.37s
2499:	learn: 0.0628617	test: 0.0400518	best: 0.0400496 (2497)	total: 59.7s	remaining: 0us
bestTest = 0.04004958153
bestIteration = 2497
Shrink model to first 2498 iterations.
0:	learn: 0.5987015	test: 0.5941226	best: 0.5941226 (0)	total: 20.6ms	remaining: 51.5s
400:	learn: 0.0978691	test: 0.0425368	best: 0.0425368 (400)	total: 5.33s	remaining: 27.9s
800:	learn: 0.0958555	test: 0.0422703	best: 0.0422703 (800)	total: 10.4s	remaining: 22.2s
1200:	learn: 0.0945135	test: 0.0421299	best: 0.0421285 (1199)	total: 15.5s	remaining: 16.8s
1600:	learn: 0.0934935	test: 0.0420773	best: 0.0420724 (1586)	total: 20.7s	remaining: 11.6s
2000:	learn: 0.0926242	test: 0.0419534	best: 0.0419534 (2000)	total: 25.9s	remaining: 6.46s
2400:	learn: 0.0918456	test: 0.0419113	best: 0.0419113 (2400)	total: 31.1s	remaining: 1.28s
2499:	learn: 0.0916628	test: 0.0419135	best: 0.0419059 (2421)	total: 32.4s	remaining: 0us
bestTest = 0.04190590541
bestIteration = 2421
Shrink model to first 2422 iterations.
0:	learn: 0.6341390	test: 0.6315473	best: 0.6315473 (0)	total: 25.6ms	remaining: 1m 4s
400:	learn: 0.0978172	test: 0.0424796	best: 0.0424796 (400)	total: 6.07s	remaining: 31.8s
800:	learn: 0.0957082	test: 0.0422310	best: 0.0422310 (800)	total: 12s	remaining: 25.5s
1200:	learn: 0.0943076	test: 0.0420624	best: 0.0420609 (1197)	total: 18s	remaining: 19.4s
1600:	learn: 0.0932147	test: 0.0419805	best: 0.0419791 (1595)	total: 23.9s	remaining: 13.4s
2000:	learn: 0.0922647	test: 0.0418728	best: 0.0418728 (2000)	total: 29.9s	remaining: 7.46s
2400:	learn: 0.0914090	test: 0.0418191	best: 0.0418190 (2375)	total: 35.8s	remaining: 1.48s
2499:	learn: 0.0912074	test: 0.0418028	best: 0.0418019 (2486)	total: 37.3s	remaining: 0us
bestTest = 0.04180194537
bestIteration = 2486
Shrink model to first 2487 iterations.
0:	learn: 0.5476003	test: 0.5403692	best: 0.5403692 (0)	total: 20.8ms	remaining: 52.1s
400:	learn: 0.0964883	test: 0.0423393	best: 0.0423341 (399)	total: 5.26s	remaining: 27.6s
800:	learn: 0.0943710	test: 0.0421452	best: 0.0421447 (799)	total: 10.4s	remaining: 22.1s
1200:	learn: 0.0928683	test: 0.0419724	best: 0.0419696 (1198)	total: 15.6s	remaining: 16.8s
1600:	learn: 0.0916592	test: 0.0419231	best: 0.0419177 (1598)	total: 20.7s	remaining: 11.6s
2000:	learn: 0.0905905	test: 0.0418627	best: 0.0418436 (1867)	total: 25.9s	remaining: 6.45s
bestTest = 0.04184361776
bestIteration = 1867
Shrink model to first 1868 iterations.
0:	learn: 0.6350804	test: 0.6323081	best: 0.6323081 (0)	total: 20.7ms	remaining: 51.8s
400:	learn: 0.0992080	test: 0.0427780	best: 0.0427721 (340)	total: 5.34s	remaining: 28s
800:	learn: 0.0972860	test: 0.0425253	best: 0.0425227 (788)	total: 10.5s	remaining: 22.3s
1200:	learn: 0.0960994	test: 0.0423592	best: 0.0423569 (1196)	total: 15.8s	remaining: 17s
1600:	learn: 0.0952002	test: 0.0422719	best: 0.0422717 (1598)	total: 20.9s	remaining: 11.7s
2000:	learn: 0.0944597	test: 0.0422006	best: 0.0422006 (2000)	total: 26.2s	remaining: 6.53s
2400:	learn: 0.0937975	test: 0.0421253	best: 0.0421253 (2400)	total: 31.4s	remaining: 1.29s
2499:	learn: 0.0936457	test: 0.0421067	best: 0.0421053 (2495)	total: 32.6s	remaining: 0us
bestTest = 0.04210530599
bestIteration = 2495
Shrink model to first 2496 iterations.

    ndcg@20                                             params  trees
1  0.096714  {'learning_rate': 0.05, 'l2_leaf_reg': 30, 'de...   2429
0  0.094945  {'learning_rate': 0.03, 'l2_leaf_reg': 10, 'de...   2500
6  0.094918  {'learning_rate': 0.05, 'l2_leaf_reg': 10, 'de...   2422
9  0.094822  {'learning_rate': 0.03, 'l2_leaf_reg': 10, 'de...   2496
8  0.094557  {'learning_rate': 0.08, 'l2_leaf_reg': 30, 'de...   1868

In [57]:
seq_cb = CatBoostClassifier(
    iterations=CB_TREES, depth=CB_DEPTH, learning_rate=CB_LR,
    loss_function='Logloss', random_seed=SEED,
    task_type='GPU' if DEVICE == 'cuda' else 'CPU', verbose=200
)
seq_cb.fit(seq_features('train', cb_rows), y_train,
           eval_set=(seq_features('valid', valid_rows), y_valid),
           early_stopping_rounds=120)

seq_scores = np.empty(valid_store.n, np.float32)
for i in tqdm(range(0, valid_store.n, 100_000)):
    r = slice(i, min(i+100_000, valid_store.n))
    seq_scores[r] = seq_cb.predict_proba(seq_features('valid', r))[:, 1]

0:	learn: 0.5942731	test: 0.5896982	best: 0.5896982 (0)	total: 41.5ms	remaining: 20.7s
200:	learn: 0.0940367	test: 0.0418447	best: 0.0418447 (200)	total: 4.75s	remaining: 7.07s
400:	learn: 0.0899828	test: 0.0415127	best: 0.0415089 (398)	total: 9.43s	remaining: 2.33s
499:	learn: 0.0884426	test: 0.0414036	best: 0.0414008 (498)	total: 11.7s	remaining: 0us
bestTest = 0.04140079816
bestIteration = 498
Shrink model to first 499 iterations.

  0%|          | 0/60 [00:00<?, ?it/s]

In [60]:
scores['AutoFE+Seq'] = seq_scores

comparison = pd.DataFrame([
    ranking_report(scores[k], valid_store, truth_valid, k)
    for k in ('R2', 'R2+ManualSeq', 'AutoFE', 'AutoFE+Seq')
])

display(comparison[['model', 'ndcg@10', 'ndcg@20', 'recall@20', 'logloss']])
comparison.to_csv(OUT / 'manual_seq_comparison.csv', index=False)

          model   ndcg@10   ndcg@20  recall@20   logloss
0            R2  0.094611  0.088879   0.064349  0.040061
1  R2+ManualSeq  0.093923  0.088704   0.064698  0.039568
2        AutoFE  0.093553  0.087792   0.064181  0.041338
3    AutoFE+Seq  0.094838  0.088924   0.065017  0.041586

## Интерпретация

In [61]:
w = 1 / np.log2(np.arange(2, 22))
ideal = np.r_[0, w.cumsum()]

def user_ndcg(pred, store, total):
    y = np.asarray(store.a['y']).reshape(N_USERS, C)
    top = np.argsort(-np.asarray(pred).reshape(N_USERS, C),
                     axis=1, kind='stable')[:, :20]
    dcg = (np.take_along_axis(y, top, axis=1) * w).sum(1)
    return np.where(total > 0, dcg / np.maximum(ideal[np.minimum(total, 20)], 1), 0)

v = {k: user_ndcg(scores[k], valid_store, truth_valid) for k in comparison.model}
rng_ci = np.random.default_rng(123)
ci = []

for a, b in [('AutoFE+Seq', 'R2'), ('AutoFE+Seq', 'AutoFE'),
             ('R2+ManualSeq', 'R2')]:
    d = v[a] - v[b]
    boot = [d[rng_ci.integers(N_USERS, size=N_USERS)].mean() for _ in range(2000)]
    ci.append((a, b, d.mean(), *np.quantile(boot, [.025, .975])))

display(pd.DataFrame(ci, columns=['model', 'baseline', 'delta_ndcg20', 'CI_low', 'CI_high']))

top = {k: np.argsort(-scores[k].reshape(N_USERS, C), axis=1)[:, :20]
       for k in ('R2', 'AutoFE+Seq')}
overlap = (top['R2'][:, :, None] == top['AutoFE+Seq'][:, None, :]).any(2).sum(1).mean() / 20
print(f'Top-20 overlap R2 vs AutoFE+Seq: {overlap:.1%}')

seq_names = learned_cols + raw_common + [f'seq_{i}' for i in range(S['valid'].shape[1]-1)] + ['seq_score']
imp = pd.Series(seq_cb.feature_importances_, index=seq_names).sort_values(ascending=False)
display(imp.head(20).rename('importance').to_frame())
print('Importance share of CandidateSeq:', round(imp[imp.index.str.startswith('seq_')].sum(), 2), '%')

files = {'R2 validation': R2/'features'/'features_valid.parquet',
         'AutoFE validation': LOCAL/'learned_valid.npy',
         'Seq validation': LOCAL/'seq_valid.npy',
         'AutoFE checkpoint': OUT/'encoder.pt',
         'Seq checkpoint': OUT/'seq_encoder.pt'}
display(pd.Series({k: round(p.stat().st_size / 2**20, 1) for k, p in files.items()}, name='MiB'))

print('Encoder parameters:', sum(p.numel() for p in encoder.parameters()),
      '| CandidateSeq parameters:', sum(p.numel() for p in seq.parameters()))

          model baseline  delta_ndcg20    CI_low   CI_high
0    AutoFE+Seq       R2      0.000045 -0.001131  0.001251
1    AutoFE+Seq   AutoFE      0.001132  0.000452  0.001821
2  R2+ManualSeq       R2     -0.000175 -0.000807  0.000461

Top-20 overlap R2 vs AutoFE+Seq: 61.0%

                   importance
itemknn_score        7.629637
decaypop_score       7.536373
latent_44            4.320953
source_is_itemknn    4.129888
latent_27            3.802414
latent_09            3.411149
latent_58            2.923957
latent_03            2.834576
latent_52            2.544461
latent_61            2.370290
latent_23            2.307079
retrieval_rank       2.301032
latent_10            2.276319
latent_42            2.259058
latent_41            2.124717
latent_37            2.064516
neural_score         1.975884
latent_40            1.928595
latent_34            1.927386
latent_35            1.900386

Importance share of CandidateSeq: 0.23 %

R2 validation        227.3
AutoFE validation    743.9
Seq validation        68.7
AutoFE checkpoint      0.4
Seq checkpoint       114.0
Name: MiB, dtype: float64

Encoder parameters: 107039 | CandidateSeq parameters: 29890349

## Тест

In [62]:
assert all(name in hist_id and name in hist_age for name in ('train', 'valid', 'test'))

In [63]:
neg_rng = np.random.default_rng(SEED + 1)
vy = np.asarray(valid_store.a['y']).reshape(N_USERS, C)
vneg = [u*C + neg_rng.choice(np.flatnonzero(vy[u] == 0),
        size=min(CB_NEG_PER_USER, (vy[u] == 0).sum()), replace=False) for u in range(N_USERS)]
vrows = np.sort(np.concatenate([np.flatnonzero(vy.ravel()), *vneg])).astype(np.int64)
y_final = np.r_[y_train, np.asarray(valid_store.a['y'][vrows], dtype=np.int8)]

def fit_features(split, rows, name):
    st = globals()[f'{split}_store']
    if name.startswith('R2'):
        x = load_manual(split, rows)[manual_cols].to_numpy(np.float32)
        return np.column_stack([x, manual_seq(split, rows)]) if name == 'R2+ManualSeq' else x
    return seq_features(split, rows) if name == 'AutoFE+Seq' else np.column_stack([
        A[split][rows], st.a['common'][rows]])

searches = {'R2': r2_search, 'R2+ManualSeq': manual_seq_search, 'AutoFE': a1_search}
final_models, training_seconds = {}, {}

for name in ('R2', 'R2+ManualSeq', 'AutoFE', 'AutoFE+Seq'):
    if name == 'AutoFE+Seq':
        p = seq_cb.get_all_params()
        hp, trees = {k: p[k] for k in ('depth', 'learning_rate', 'l2_leaf_reg')}, seq_cb.tree_count_
    else:
        best = searches[name].iloc[0]
        hp, trees = best['params'], int(best['trees'])

    X = np.vstack([fit_features('train', cb_rows, name), fit_features('valid', vrows, name)])
    t = time.perf_counter()
    model = CatBoostClassifier(**hp, iterations=trees, loss_function='Logloss',
        task_type='GPU' if DEVICE == 'cuda' else 'CPU', random_seed=SEED, verbose=200)
    model.fit(X, y_final)
    training_seconds[name] = round(time.perf_counter() - t, 1)
    model.save_model(str(OUT / f'{name.replace("+", "_")}_final.cbm'))
    final_models[name] = model
    print(name, len(X), 'rows,', trees, 'trees,', training_seconds[name], 's')
    del X
    gc.collect()

pd.Series(training_seconds, name='train_seconds').to_csv(OUT/'final_training_cost.csv')

0:	learn: 0.6373289	total: 46.1ms	remaining: 1m 54s
200:	learn: 0.1009245	total: 5.6s	remaining: 1m 4s
400:	learn: 0.0979915	total: 11s	remaining: 57.4s
600:	learn: 0.0961786	total: 16.5s	remaining: 52s
800:	learn: 0.0948938	total: 21.8s	remaining: 46.2s
1000:	learn: 0.0937834	total: 27.3s	remaining: 40.9s
1200:	learn: 0.0929130	total: 32.7s	remaining: 35.3s
1400:	learn: 0.0920975	total: 38.1s	remaining: 29.8s
1600:	learn: 0.0913650	total: 43.5s	remaining: 24.4s
1800:	learn: 0.0906812	total: 49s	remaining: 18.9s
2000:	learn: 0.0900834	total: 54.4s	remaining: 13.5s
2200:	learn: 0.0895234	total: 60s	remaining: 8.07s
2400:	learn: 0.0889747	total: 1m 5s	remaining: 2.62s
2496:	learn: 0.0887184	total: 1m 8s	remaining: 0us
R2 2074770 rows, 2497 trees, 72.4 s
0:	learn: 0.6022295	total: 52ms	remaining: 2m 9s
200:	learn: 0.0986046	total: 5.74s	remaining: 1m 5s
400:	learn: 0.0957713	total: 11.3s	remaining: 59.1s
600:	learn: 0.0938879	total: 16.8s	remaining: 53.1s
800:	learn: 0.0925108	total: 22.4s	remaining: 47.4s
1000:	learn: 0.0913604	total: 27.9s	remaining: 41.7s
1200:	learn: 0.0902905	total: 33.5s	remaining: 36.2s
1400:	learn: 0.0893475	total: 39.1s	remaining: 30.6s
1600:	learn: 0.0885296	total: 44.7s	remaining: 25s
1800:	learn: 0.0877348	total: 50.3s	remaining: 19.4s
2000:	learn: 0.0870384	total: 55.9s	remaining: 13.8s
2200:	learn: 0.0863779	total: 1m 1s	remaining: 8.25s
2400:	learn: 0.0857368	total: 1m 7s	remaining: 2.66s
2495:	learn: 0.0854559	total: 1m 9s	remaining: 0us
R2+ManualSeq 2074770 rows, 2496 trees, 76.0 s
0:	learn: 0.5947801	total: 50.2ms	remaining: 2m 5s
200:	learn: 0.0990718	total: 5.96s	remaining: 1m 8s
400:	learn: 0.0972263	total: 11.8s	remaining: 1m 1s
600:	learn: 0.0960185	total: 17.6s	remaining: 55.5s
800:	learn: 0.0951250	total: 23.4s	remaining: 49.5s
1000:	learn: 0.0943500	total: 29.2s	remaining: 43.6s
1200:	learn: 0.0936326	total: 35s	remaining: 37.8s
1400:	learn: 0.0930252	total: 40.9s	remaining: 32s
1600:	learn: 0.0924537	total: 46.7s	remaining: 26.1s
1800:	learn: 0.0919241	total: 52.5s	remaining: 20.3s
2000:	learn: 0.0914278	total: 58.3s	remaining: 14.5s
2200:	learn: 0.0909529	total: 1m 4s	remaining: 8.63s
2400:	learn: 0.0904997	total: 1m 10s	remaining: 2.8s
2496:	learn: 0.0903017	total: 1m 12s	remaining: 0us
AutoFE 2074770 rows, 2497 trees, 80.8 s
0:	learn: 0.5925668	total: 69.7ms	remaining: 34.7s
200:	learn: 0.0968120	total: 8.03s	remaining: 11.9s
400:	learn: 0.0939856	total: 15.9s	remaining: 3.88s
498:	learn: 0.0929255	total: 19.7s	remaining: 0us
AutoFE+Seq 2074770 rows, 499 trees, 28.1 s

In [78]:
for name in ('train_store', 'valid_store', 'r2_train', 'r2_valid', 'a1_train',
             'a1_valid', 'Xtr', 'Xva', 'man_train', 'man_eval', 'mem_train',
             'mem_valid', 'manual', 'automatic', 'scores', 'seq_scores', 'pred'):
    globals().pop(name, None)
gc.collect()
ctypes.CDLL('libc.so.6').malloc_trim(0)
RAM_SHARE = 0.70

c_test = load_main_candidates('test')
cols_test = ['uid', 'item_id', 'group_id', 'label', 'retrieval_rank',
             'itemknn_score', 'decaypop_score', 'retrieval_source']
c_test = c_test[cols_test].copy()
gc.collect()
folder = LOCAL/'store_test'
if not store_ready('test', c_test, int(snaps.loc['test'].history_end)):
    shutil.rmtree(folder, ignore_errors=True)
    create_store('test', c_test, int(snaps.loc['test'].history_end))
del c_test
gc.collect()

test: compact observed mapping
test: indexing 23.6s, events=47,550,037, ui=2,279,851, ua=1,450,640
test: RAM staging 2.88 GiB / budget 3.00 GiB
test: event aggregation 908.3s
  ui: 2,279,852 rows, 5,646,992 nonempty time bins
  ua: 1,450,641 rows, 5,207,587 nonempty time bins
test: save and compression 55.7s
test history events 47,550,037 pairs 6,000,000 stored ui 2,279,851 stored ua 1,450,640 seconds 992.0

In [86]:
A = {s: np.load(LOCAL/f'learned_{s}.npy', mmap_mode='r')
     for s in ('train', 'valid')}
S = {s: np.load(LOCAL/f'seq_{s}.npy', mmap_mode='r')
     for s in ('train', 'valid')}

In [82]:
assert 'test' in hist_id and 'test' in hist_age

In [83]:
test_store = RelationStore('test')

if not feature_ready(LOCAL/'learned_test.npy', (test_store.n, Z_DIM+1), OUT/'encoder.pt', 'test'):
    encoder.load_state_dict(torch.load(OUT/'encoder.pt', map_location=DEVICE, weights_only=True))
    extract_features('test', test_store)

if not feature_ready(LOCAL/'seq_test.npy', (test_store.n, 6), OUT/'seq_encoder.pt', 'test'):
    seq.load_state_dict(torch.load(OUT/'seq_encoder.pt', map_location=DEVICE, weights_only=True))
    tmp = LOCAL/'seq_test.partial.npy'
    feat = np.lib.format.open_memmap(tmp, mode='w+', dtype=np.float16,
                                    shape=(test_store.n, 6))
    for p in tqdm(range(0, test_store.n, 4096), desc='Seq test'):
        r = np.arange(p, min(p+4096, test_store.n))
        feat[p:p+len(r)] = seq_predict('test', test_store, r, features=True).astype(np.float16)
    feat.flush()
    del feat
    finish_feature(tmp, LOCAL/'seq_test.npy', (test_store.n, 6), OUT/'seq_encoder.pt', 'test')

A['test'] = np.load(LOCAL/'learned_test.npy', mmap_mode='r')
S['test'] = np.load(LOCAL/'seq_test.npy', mmap_mode='r')
assert_alignment('test', test_store)

sc = {name: np.empty(test_store.n, np.float32) for name in final_models}
a = np.load(LOCAL/'learned_test.npy', mmap_mode='r')
s = np.load(LOCAL/'seq_test.npy', mmap_mode='r')

for p in tqdm(range(0, test_store.n, 100_000), desc='AutoFE test'):
    r = slice(p, min(p+100_000, test_store.n))
    x = np.column_stack([a[r].astype(np.float32), test_store.a['common'][r]])
    sc['AutoFE'][r] = final_models['AutoFE'].predict_proba(x)[:, 1]
    sc['AutoFE+Seq'][r] = final_models['AutoFE+Seq'].predict_proba(np.column_stack([x, s[r]]))[:, 1]

p = 0
for b in tqdm(pq.ParquetFile(R2/'features'/'features_test.parquet').iter_batches(
             batch_size=100_000, columns=list(dict.fromkeys(manual_cols + ['uid', 'item_id', 'group_id']))), desc='Manual test'):
    f = b.to_pandas()
    x = f[manual_cols].to_numpy(np.float32)
    r = slice(p, p+len(x))
    sc['R2'][r] = final_models['R2'].predict_proba(x)[:, 1]
    sc['R2+ManualSeq'][r] = final_models['R2+ManualSeq'].predict_proba(
        np.column_stack([x, manual_seq('test', r)]))[:, 1]
    p += len(x)

assert p == test_store.n, 'Test row count mismatch'

truth_test = future_totals('test')
test_results = pd.DataFrame([ranking_report(sc[k], test_store, truth_test, k) for k in sc])
display(test_results[['model', 'ndcg@10', 'ndcg@20', 'recall@20', 'logloss']])
test_results.to_csv(OUT/'final_test_metrics.csv', index=False)

d = user_ndcg(sc['AutoFE+Seq'], test_store, truth_test) - user_ndcg(sc['R2'], test_store, truth_test)
rg = np.random.default_rng(123)
ci = np.quantile([d[rg.integers(N_USERS, size=N_USERS)].mean() for _ in range(2000)], [.025, .975])
print('Seq − R2 delta NDCG@20:', d.mean(), '95% bootstrap CI:', ci)

comparisons = []
for left, right in [('AutoFE', 'R2'), ('AutoFE+Seq', 'AutoFE'),
                    ('R2+ManualSeq', 'R2'), ('AutoFE+Seq', 'R2+ManualSeq')]:
    diff = user_ndcg(sc[left], test_store, truth_test) - user_ndcg(sc[right], test_store, truth_test)
    generator = np.random.default_rng(SEED + 2026)
    boot = [diff[generator.integers(N_USERS, size=N_USERS)].mean() for _ in range(2000)]
    comparisons.append(dict(model=left, baseline=right, delta_ndcg20=float(diff.mean()),
                            CI_low=float(np.quantile(boot, .025)),
                            CI_high=float(np.quantile(boot, .975))))
pd.DataFrame(comparisons).to_csv(OUT/'final_test_bootstrap.csv', index=False)

AutoFE test:   0%|          | 0/60 [00:00<?, ?it/s]

Manual test: 0it [00:00, ?it/s]

          model   ndcg@10   ndcg@20  recall@20   logloss
0            R2  0.093081  0.088039   0.064351  0.040463
1  R2+ManualSeq  0.093645  0.088626   0.064535  0.039895
2        AutoFE  0.093513  0.088317   0.064728  0.041310
3    AutoFE+Seq  0.093693  0.088379   0.064351  0.041567

Seq − R2 delta NDCG@20: 0.0003398964661963543 95% bootstrap CI: [-0.0007042   0.00140833]

## Инференс

In [88]:
from time import perf_counter

n = 50000
r = np.arange(n)

m = next(pq.ParquetFile(
    R2 / 'features' / 'features_test.parquet').iter_batches(batch_size=n)).to_pandas()[manual_cols].to_numpy(np.float32)

a = np.asarray(A['test'][r], dtype=np.float32)
s = np.asarray(S['test'][r], dtype=np.float32)
common = test_store.a['common'][r]

xs = {
    'R2': m,
    'R2+ManualSeq': np.column_stack([m, manual_seq('test', r)]),
    'AutoFE': np.column_stack([a, common]),
    'AutoFE+Seq': np.column_stack([a, common, s])
}

for name, x in xs.items():
    model = final_models[name]
    model.predict_proba(x)
    measurements = []
    for _ in range(7):
        t = perf_counter()
        model.predict_proba(x)
        measurements.append(perf_counter() - t)
    sec = float(np.median(measurements))
    print(f'{name}: median {sec:.3f} s / {n:,} rows, '
          f'{n / sec:,.0f} rows/s; trees={model.tree_count_}')

R2: 0.131 s / 50,000 rows, 382,042 rows/s
R2+ManualSeq: 0.155 s / 50,000 rows, 322,502 rows/s
AutoFE: 0.180 s / 50,000 rows, 278,406 rows/s
AutoFE+Seq: 0.073 s / 50,000 rows, 685,083 rows/s